### ISSUE TITLE
tnbuser.com   /   tnbeverything.com

### ISSUE THREAD

**Issue by stweyel** [thenewboston-developers/Projects#167]
### How would you describe your project?
establishing a website which provides easy access to:
⁃ TNB information/FAQs/Wiki/How Tos/Tutorials
⁃ TNB related websites (comprehensive collection of links - comparable to e.g. https://nanolinks.info/)
⁃ actual information (e.g. list of banks, network status etc.)
⁃ link to social platforms
⁃ active TNB projects (games, apps, dapps, faucet etc.) open for participation
⁃ link TNBC related platforms/information etc.
⁃ project promotions
⁃ maybe some fun stuff
⁃ everything in the 'TNB world' what could be of interest …from a USER/coin OWNER perspective.

### What problem does it solve?
⁃ Provide users (with or without background, knowledge or interest in development) easy access to TNB related content.
⁃ Separate sometimes overwhelming development subjects from ‚enduser‘ subjects.
⁃ Provide a central source of information which would potentially clutter the main TNB website. 
⁃ Provide a lightweight entry point to TNB.

### Who is the target market?
TNB'C' holders / everyone who’s interested in the TNB project

### How will this project benefit the network and/or the community?
Providing a maintained, curated and central list of everything TNB'C' related.
Increase TNB popularity through a comprehensive TNB portal.

### How does it integrate with thenewboston digital currency work?
It’s all about TNB

### What is the estimated completion date for this project? (rough estimates are acceptable)
Q3, 2021

### What is your Discord username?
stw#0279

### Roadmap
- Milestone 1: Aquire domain / create landing page wireframe   - 1 wap  <=> weeks after approval
- Milestone 2: Layout of content / Complete Sitemap wireframe  - 2 wap
- Milestone 3: Design & outline of website layout - 4 wap
- Milestone 4: Connection to a CMS - 4 wap
- Milestone 5-9: Content Implementation - 8 wap
- Milestone 10: Final release - 10 wap

### Milestone Description
Milestone 1: Aquire domain. Create a landing page wireframe/UX overview. This is subject to change on later progress and changing preconditions due to altering demands.

Actual tech stack: React/next.js CMS: Contentful
### Requested Payment Upon Completion
76000

| # | Objective           | Estimated Value (coins)   |
| - | ------------------- | ------------------------- |
| 1 |Aquire domain / Landing page wireframe   | 4000 					  |
| 2 |Layout of content / Complete Sitemap wireframe   | 6000 					  |
| 3 |UI Design / preview online		  | 18000 					  |
| 4 |Implementing CMS | 4000 					  |
| 5 |Implementing social links and apis / article previews					  | 6000 					  |
| 6 |Implementing wiki framework				  | 5000 					  |
| 7 |Writing and implementing beginners guide	  | 4000 					  |
| 8 |Adding and completing content (Projects/Weblinks/Documentation/Wiki etc.) | 15000 						  |
| 9 |Implementing tnbc widgets/account infos etc.  | 6000 					  |
| 10 |Finalizing and official release | 8000 					  |

Project Account
3a115cb6d87edb299e0ca95393465d171768bb5c2c08c4b27e1cfb4c3141f8ec

**Comment by tomijaga** [comment]
Hey @stweyel, like the project idea. What do u think about creating a wiki were all this information can be displayed. It would look something like this https://docs.requarks.io/

**Comment by stweyel** [comment]
Hey @tomijaga, wiki would be one important part of the project. Things are happening right now. IIRC Kristy Lee recently started a WIKI repo (which i can't find anymore). So things have to be cleared up a bit before distributing work.
However we should wait for the approval before investing time and energy in things which may be wrecked afterwards.

**Comment by SazidAhmed** [comment]
A nice idea with TNBC. 
I'm a full-stack web developer and currently working on one of the project of The New Boston called  "Restaurant Self Order App".
I'm willing to contribute on your project as a web developer.
Here's my Discord : SazidAhmed#8192
Feel free to contact me when you'll need a web developer.

**Comment by geekfahim** [comment]
Hi, I am Fahim Ahmed . I have been working on the tech field around 7 years. I have experience of 2 years as a Lead Engineer . I am full stack developer & currenly working with django. 
I'm willing to contribute my skills as a Django Developer .
My Discord id : devfahimahmed#1407
Feel free to contact with me .

**Comment by Ali-Ar-Reza** [comment]
I'm a UI/UX designer and do design and prototype with Figma.
If you want to see my skills, there are some sample projects attached to my github repositories. 
If there are any opening for designers ping me on discord : Sazid#1369 .
Thank You

**Comment by manishram** [comment]
Hey, @stweyel please update your proposal with a new proposal format and details.
Check the new project proposal format [HERE](https://github.com/thenewboston-developers/Projects/issues/new?assignees=&labels=Project&template=project-proposal.md&title=NAME_OF_YOUR_PROJECT)

**Comment by stweyel** [comment]
@manishram  done [x]

**Comment by stweyel** [comment]
testing version online: http://www.tnbeverything.com/

**Comment by manishram** [comment]
Hey @stweyel, we are going to have a further meeting with the marketing team regarding this project.

**Comment by angle943** [comment]
The government likes the idea! but a few things to discuss:

1. `TNB'C' trading/exchange platforms etc.` - For legal reasons, we cannot fund any project that deals with exchanges. So let's remove this from the project.
2. `TNBC/USDT 0.27` - again, for legal reasons, we cannot have this in the document.

We like the idea, but there are a couple issues that we see with the milestones you have presented:

1. What milestone has been completed so far, and what milestone is next? 
2. Milestones should be auditable proof of work, meaning they should be something you can present to the auditors, and the auditor can clearly access whether it has been completed or not. For example, `Development and programming` - it is imposibble to determine when this has been completed.

Because of the above issue, we are going to ask that you revamp your roadmap and milestone in a quantifiable way.

**Comment by angle943** [comment]
approved, and milestone 1 approved for 76,000!

**Comment by manishram** [comment]
Project Repo: https://github.com/stweyel/tnbuser.com-tnbeverything.com
