### ISSUE TITLE
Upwork for TNBC

### ISSUE THREAD

**Issue by hussu010** [thenewboston-developers/Projects#171]
I'll submit the project proposal once the new format is out. Just having this here so no one will make the same project proposal.

**Comment by SazidAhmed** [comment]
I'll contribute on this project proposal once the project proposal is approved . Just having this here so I become the fist contributor.

**Comment by manishram** [comment]
Hey, @dhakal0kushal new project proposal format is [HERE](https://github.com/thenewboston-developers/Projects/issues/new?assignees=&labels=Project&template=project-proposal.md&title=NAME_OF_YOUR_PROJECT). Please update with details.
