### ISSUE TITLE
TNBC JS SDK

### ISSUE THREAD

**Issue by zinoadidi** [thenewboston-developers/Projects#176]
# Project Details
#### How would you describe your project?
Javascript SDK / library for third-party developers and projects using TNBC chain or interested in accessing TNBC blockchain API functionalities without having to connect to multiple APIs by themselves directly. 

#### What problem does this project solve?
While it is true that users can access directly the APIs and make their own implementation of various chain related logic, there is a need for a more coordinated approach, one that aligns with industry trends as most projects in present day no longer access third party APIs directly but rather use tested, trusted SDKs which contains latest security fixes as well as scrutinised implementation of various chain related logic. 
In summary, The following outline is in order:

- Ease of access to all important TNBC related functionalities for third parties 
- Avoiding insecure implementation of on-chain related features across multiple third party projects
- Availability of an alternative, non-commercial solution to accessing different TNBC functionalities for third party projects using JS
- Provision of latest security fixes and updates in real-time, projects may have a faulty implementation that is not updated in time

#### Who is the target market?
Third-party projects and developers who are interested in using TNBC functionalities (transaction, signing, etc) in their projects and want more flexibility in how their activities with the chain are managed and do not want to use API calls directly / implement all the smaller details surrounding the API calls by themselves.

#### How will this project benefit the network and/or the community?
More projects can easily join/integrate TNBC functionalities with this SDK since they can download the SDK and start development in seconds
All projects who use the SDK can get access to the latest security fixes and updates in real-time and do not have to worry about maintaining the TNBC side of the implementation

#### How is this project centered around thenewboston?
TNBC JS SDK is a not-for-profit wrapper around the existing blockchain APIs and functionalities, all features and functionalities provided through the SDK are coming directly from the chain. Development activities on the SDK are closely tied to developments on the various backends / APIs of the chain. If new functionalities are created on-chain, the SDK implements them using contributors and makes them available for end-users. 

#### What is the estimated completion date for this project? (rough estimates are acceptable)
The project continues as long as new functionalities or fixes are made to the chain. ALPHA, BETA and Post BETA changes made to the chain will all be reflected on the SDK

#### Please include a detailed roadmap for your project below. This must include a list of all milestones where payments will be awarded upon completion of each.
Since development of the JS SDK is tightly coupled with the chain development, we can afford a roadmap with loose milestones. Based on available data, and the general goal of the SDK team, the following roadmap and milestones are submitted.
 
- Complete roadmap documentation >> https://docs.google.com/document/d/1DMZQ2bSN_HGvLw37U8AfPgwOgQOiweSJUF-bWUvobew/edit?usp=sharing
- List of all created milestones >> https://github.com/thenewboston-developers/thenewboston-js/milestones?direction=asc&sort=title

Key points from roadmap and prospective milestones: 
1. Finalizing Tests and Documentation for Existing Classes
   * Milestones: 
       - https://github.com/thenewboston-developers/thenewboston-js/milestone/2
       - https://github.com/thenewboston-developers/thenewboston-js/milestone/1
       - TBD
2. Implementation of missing functionalities on SDK
   More information on functionalities not yet implemented here https://docs.google.com/document/d/1FaPq2stWP0lMtHATNIfLA6ryMd0PtUYdcnrvZbUk7FI/edit
   * Milestones: 
       - https://github.com/thenewboston-developers/thenewboston-js/milestone/3
       - TBD
3. Integration of SDK (ALPHA) functionalities With Account Manager
   * Milestones: 
       - https://github.com/thenewboston-developers/thenewboston-js/milestone/5
       - https://github.com/thenewboston-developers/thenewboston-js/milestone/7
       - https://github.com/thenewboston-developers/thenewboston-js/milestone/6
       - https://github.com/thenewboston-developers/thenewboston-js/milestone/10
       - https://github.com/thenewboston-developers/thenewboston-js/milestone/8
       - https://github.com/thenewboston-developers/thenewboston-js/milestone/9
       - https://github.com/thenewboston-developers/thenewboston-js/milestone/11
       - TBD
4. Implementation of new functionalities in ALPHA (Memo, etc)
   * Milestones: 
       - https://github.com/thenewboston-developers/thenewboston-js/milestone/4
5. Implementation of BETA Functionalities
   * Milestones: 
       - TBD
6. Facilitate Usage of JS SDK for Integration of BETA changes in Account Manager
   * Milestones: 
       - TBD
7. Sync Development of JS SDK with BETA Development Timeline
   * Milestones: 
       - TBD
8. Third-party Development Tool Compliance
   * Milestones: 
       - TBD
9. Post BETA development
   * Milestones: 
       - TBD

#### What is your Discord username?
ZinoAdidi @zinoadidi#1554 

#### Additional files and documentation including architectural diagrams, wireframes, research documents, visuals, etc… (optional)
- TNBC JS SDK is available as an NPM package here https://www.npmjs.com/package/thenewboston
- Project link/ git repo https://github.com/thenewboston-developers/thenewboston-js
- All tasks and processes can be tracked at https://github.com/thenewboston-developers/thenewboston-js/issues and https://github.com/thenewboston-developers/thenewboston-js/projects
- More information about the project and internal processes can be found at https://github.com/thenewboston-developers/thenewboston-js

# Milestone Details

Please include a detailed breakdown of the first milestone including a list of all quantifiable objectives and 
estimated coin value of each. Upon completion of the milestone, each objective will be reviewed by thenewboston team 
and once all objectives have been verified as completed, coins will then be rewarded.

Note that all future detailed milestone breakdowns will be written as a separate GitHub issue. Only the first one is 
included in the project proposal.

---

#### Milestone Description
Implement Missing Features that are present in TNB Account Manager but not present in the JS SDK https://github.com/thenewboston-developers/thenewboston-js/milestone/3
Roadmap Item: 2
Milestone SN: RM2:M1

#### Requested Payment Upon Completion
26000

| # | Objective           | Estimated Value (coins)   | Estimated Time   |
| - | ------------------- | ------------------------- |  ------------------------- |
| 1 | Update SignedMessage (Prereq for crawl and clean) https://github.com/thenewboston-developers/thenewboston-js/issues/95 | 2500 | 2.5 hours
| 2 | Implement craw functionality (feature, tests, docs) https://github.com/thenewboston-developers/thenewboston-js/issues/85 | 5000 | 5 hours
| 3 | Get transaction fee from node (feature, tests, docs) https://github.com/thenewboston-developers/thenewboston-js/issues/87 | 2500 | 2.5 hours
| 4 | Gets the PV set for a bank (feature, tests, docs)  https://github.com/thenewboston-developers/thenewboston-js/issues/84 | 3000 | 3 hours
| 5 | Report on missing features on TNB-JS that are in account manager https://github.com/thenewboston-developers/thenewboston-js/issues/73   | 5000 | 5 hours
| 6 | Bulk payments  (feature, tests, docs) https://github.com/thenewboston-developers/thenewboston-js/issues/83 | 5000 | 5 hours
| 7 |  Remove disconnected nodes functionality (feature, tests, docs) https://github.com/thenewboston-developers/thenewboston-js/issues/86 | 3000 | 3 hours

### Calculation used for assigning tnbc to tasks
1 Minute of work time =  16  tnbc
1 hour of work time = 1000 tnbc

Proposed Rate: 
[ ![TNBC/USD](https://img.shields.io/endpoint?link=https://tnbcgames.github.io/TNBCUtil/github/&color=red&label=TNBC%2FUSD&style=plastic&url=https%3A%2F%2Ftnbcgames.github.io%2FTNBCUtil%2Fgithub%2Frate-badge.json) ](https://tnbcrow.pythonanywhere.com)

### Project Wallet
79f58f305ff26588e30dc52f0d4f75f24a2c073e2e64ab5ce9d58abb5a8f6fe2

**Comment by zinoadidi** [comment]
Project link/ git repo https://github.com/thenewboston-developers/thenewboston-js

**Comment by zinoadidi** [comment]
@manishram do I need to do something more or is this all. 
Maybe add some tags or something?

**Comment by manishram** [comment]
@zinoadidi looks good to me. Just need to wait. We are working on few more documents.

After that we'll start reviewing project proposals.

**Comment by angle943** [comment]
@zinoadidi what is the estimated time needed (in hours) and the estimatred due date for each of the milestones?

**Comment by zinoadidi** [comment]
@angle943 its not very easy to scope time and due dates for future milestones that rely on contributors especially when the overall ecosystem of the project depends largely on what happens with the chain itself.

The best bet for figuring out how much time it takes is somewhere at the beginning of respective milestones;

For the first milestone added to the proposal and for future milestone, i have added the calculation that is used to determine the amount of coins distributed per task

**Comment by angle943** [comment]
btw @zinoadidi on a random note, me and Bucky are planning on adding the memo to the blockchain this weekend. Just giving you a heads up

**Comment by zinoadidi** [comment]
Do keep us in the loop @angle943 we would like to have feature in SDK as well asap.

**Comment by zinoadidi** [comment]
hi @angle943, just checking, what's the update with the review process for this project.
I am a bit reluctant to push for more work with the contributors as we still don't know what is possible / not possible with it

**Comment by angle943** [comment]
@manishram can you check on this?

**Comment by manishram** [comment]
Hey, @zinoadidi expect the review process done in 24-36 hours. Sorry for the delay.

**Comment by buckyroberts** [comment]
Closing since @angle943 will be making a bounty for payments and moving work to core team.
