### ISSUE TITLE
Digital Art buying and selling APP

### ISSUE THREAD

**Issue by gautamkmahato** [thenewboston-developers/Projects#177]
# Project Details

#### How would you describe your project?
A platform(website/ app) where people can buy and sell digital Art using blockchain technology.

#### What problem does this project solve?
The platform will provide a certificate of ownership to an item like NFT. It will help people to buy and sell items easily. In today’s world, it's very difficult to sell digital arts due to the ownership problem. so the website/app will provide a platform where digital art can be easily buy and sell using blockchain technology. 

#### Who is the target market?
Everyone but especially Artist and collectors(buyers)

#### How will this project benefit the network and/or the community?
This project is inspired by NFT technology. The platform will provide a digital signature to an item which will help us to provide a certificate of ownership to that item and people can easily buy and sell it. The platform can be a bridge between buyers and sellers.

#### How is this project centered around thenewboston?
This service is, particularly for thenewboston. All payment will be done on TNBC. 
As mentioned above this website/app completely wraps around Thenewboston cryptocurrency as a digital payment form for selling and buying items.
People can use TNB coin for buying and selling also the blockchain will help the artist to provide a digital signature to their art which will provide them a certificate of ownership.

#### What is the estimated completion date for this project? (rough estimates are acceptable)
Between 3-6 months

#### Please include a detailed roadmap for your project below. This must include a list of all milestones where payments will be awarded upon completion of each.
1. The artist/seller would upload his item which would automatically get a digital signature and will be added to the blockchain. Now the seller can put the item for sale. After that, anyone can bid an offer for that item, if he will be the highest bidder for the assigned time then he can buy the item using the TNB coin.
2. The buyers after registering to the site can buy special credits with their TNB coins. Now if someone wants to retrieve their coins he just exchanges the credits back to coins, After the bidding completion the transaction happens and the seller/buyer gets coins back to his account, which will be helpful for us to monitor the transaction.
3. Just like in real life the highest bidder would get the item and the credits/ TNB coins would be transferred to the seller. 

#### What is your Discord username?
gautam#6015

# Milestone Details

Milestone 1: 30th April 2021
- complete the website design
- completion of the frontend part like the design of the website layout, login/signup, creating the profile, uploading, images, navigation, landing page, dashboard, profile, etc.

#### Milestone Description
Milestone 1 will be the design of the website layout, completion of the frontend part like login/signup, creating the profile, uploading, images, navigation, landing page, dashboard, profile, etc.

#### Requested Payment Upon Completion
Milestone 1: 30th April 2021
- complete the website design
- Completion of website frontend parts like navigation, landing page, dashboard, profile, and some basic features.

Requested Payment Upon Completion
15,000 coins

**Comment by mrbusysky** [comment]
This can't really be done or even tested until beta or the testnet with the new node is complete. Just a heads up.

**Comment by gautamkmahato** [comment]
thanks for the reply, I am aware of the issue I know that I can't test the idea properly now but in the meantime, I can work on the website like the entire frontend and backend part and when the beta will be released I will try to implement the blockchain/TNB coin part

**Comment by manishram** [comment]
Hey, @gautamkmahato in the **Milestone Details** section you have to only include a detailed breakdown of the **first milestone** including a list of all quantifiable objectives and estimated coin value of each. 

All future detailed milestone breakdowns will be written as a **separate GitHub issue** [HERE](https://github.com/thenewboston-developers/Projects/issues/new?assignees=&labels=&template=milestone-proposal.md&title=NAME_OF_PROJECT+-+NAME_OF_MILESTONE+-+MILESTONE_NUMBER). Only the first one is included in the project proposal.

**Comment by manishram** [comment]
Hey @gautamkmahato,
- Would you be able to work on this without smart contracts? We don't have smart contracts yet.
- Need to work on the roadmap
- Not rejected but not approved yet

**Comment by gautamkmahato** [comment]
@manishram I think I can build the website without the smart contracts for now. I will add the roadmap in the project file.

**Comment by angle943** [comment]
Hey @gautamkmahato , the government has reviewed this project proposal.

We like the idea, but because support for NFT within the TNBC ecosystem is so far away, unfortunately we decided to not proceed with this project. Once we are closer to NFT integration, we can reopen this project proposal.
