### ISSUE TITLE
Get It Now

### ISSUE THREAD

**Issue by SazidAhmed** [thenewboston-developers/Projects#182]
GET IT NOW
# Project Details

#### How would you describe your project?
The need for products which are not at all imported, created or available in particular countries is a problem we deal with regularly. Certain delivery platforms (Fedex, UPS) are overpriced and still requires a longer period of delivery time compared to hands-on pick up and delivery at a designated pick up location and time.

A person (traveller) to person (client), product delivery application, across countries. The person (traveller) travelling immediately by plane buys and takes the requested product (commodity) to another country where the product receiver (client) resides.

#### What problem does this project solve?
An urgent need to fulfil a foreign product necissity in a relatively shorter time frame. An user case scenario will be if I run out of "vanilla extract" at my restaurant in Indonesia and the product is not available in the whole country, I will have to wait for an expensive emergency Fedex or UPS delivery. Instead if someone coming on the next plane from eg. USA to Indonesia can pick up the vanilla extract and bring it to me, a lot of time and extra cost can be reduced.

The goal is to get access to a wide variety of inaccessible products from another country from which the traveller will purchase and carry the product to the country the receiving party is residing. This will deliver a product and satisfy need at the fastest time possible.

#### Who is the target market?
People with no availability to particular products in foreign countries, on an emergency requirement basis.

Consumers will be able to post their required product(s) so travellers can browse to see which product they prefer or can carry and deliver. On another section travellers can post their location of departure and carraige weight for customers to find them faster to make an order request. 

#### How will this project benefit the network and/or the community?
The usage of TNBC to be paid by the TNBCrow Escrow system upon completion of agreements and the TNBCrow Escrow system used for dispute resolution will attract many users to expand and further solidify the TNBC ecosystem.

#### How is this project centered around thenewboston?
The TNBC Escrow project will be used for dispute resolution. TNBC should be used to pay for the product/s and transfer costs. This will eliminate various foreign currency payments' inconsistency.

#### What is the estimated completion date for this project?
Depending on our 7 milestones we expect to finish by August 2021.

#### Please include a detailed roadmap for your project below. This must include a list of all milestones where payments will be awarded upon completion of each.
The detailed Roadmap of all milestones :

Milestone 1: Authentication, profile and roles
		
	Objective 1: UI/UX Design of Page design of Website Home, User-Registration, Email-Confirmation, User-Signin, Password-Reset, User-Profile, user-profile-setting, admin-panel-layout , all-user-management, user-role-permission-management
	
	Objective 2: Server Development of User-Registration, Email-Confirmation, User-Signin, Password-Reset, view-user-profile, update-user-profile, user-password-change, CRUD methods for user-role-perrmission

	Objective 3: Management & Architecture of Wireframe and UML 

Milestone 2: User/ GIN ~ TNBC Incoming/ Outgoing Account API Integration
	
	Objective 1: UI/UX Design of Portal-Admin Category CRUD page, My-Items page, Create Item page, Edit Item page, My-Pickups page, Create Pickup page, Edit Pickup page, General-Items Homepage, General-single Item view page, General-Pickups home page, General- single Pickup view home page.
	
	Objective 2: Server Development of Category [list, single view, create, update, delete, Item [create, list, single-view, update, delete], Pickup Post [create, list, single-view, update, delete], show Items in Item home page, filter item in Item home page, paginate item in Item home page, show details of single item, show posts in pickup home page, filter posts in pickup home page, paginate posts in pickup home page, show details of single pickup, Topup of GIN TNBC account from User TNBC account,
	
	Objective 3: Frontend Development of Landing-Page, User-Registration, User-type Create, Email-Confirmation, User-Signin, Password-Reset, User-Profile, Portal-Admin Section, Role Permission

Milestone 3: Agreement (Carrier Perspective)

	Objective 1: UI/UX Design of carrier agreement page, buyer agreement page, portal-admin agreement list page, portal-admin agreement view page
	
	Objective 2: Server Development of createAgreementByCarrier, addItemToAgreement, setDeliveryType, buyerAccepts, agreementProofsStageTwo, buyerAgrees, agreementProofsStageThree, calculateTotalChargeTNBC, topupToGIN, agreementProofStageFour 
	
	Objective 3: Frontend Development of Portal-Admin Category CRUD page, My-Items page, Create Item page, Edit Item page, My-Pickups page, Create Pickup page, Edit Pickup page, General-Items Homepage, General-single Item view page, General-Pickups home page, General- single Pickup view home page.

Milestone 4: Agreement (Buyer Perspective) & Progress

	Objective 1: UI/UX Design of carrier Progress page, buyer Progress page, portal-admin Progress page, My-Pickups agreements page, My-Items agreements page
	
	Objective 2: Server Development of createAgreementByBuyer, addItemsByCarrier, buyerAccepts, carrierAccepts, My-Pickups agreements, My-Items agreements,  Portal-admin agreementList, Portal-admin agreementView, filterAgreement, agreementIncheckAgreementViewProgress
	
	Objective 3: Frontend Development of carrier agreement page, buyer agreement page, portal-admin agreement list page, portal-admin agreement view page

Milestone 5: TNBCrow Escrow API Integration & Dispute Resolution

	Objective 1: UI/UX Design of Escrow agreement page, escrow arbitration page
	
	Objective 2: Server Development of completeRequestToEscrow, submitDisputeTypeToEscrow, 
	
	Objective 3: Frontend Development of carrier Progress page, buyer Progress page, portal-admin Progress page, My-Pickups agreements page, My-Items agreements page

Milestone 6: Moderation

	Objective 1: UI/UX Design of Moderating page
	
	Objective 2: Server Development of Moderation 
	
	Objective 3: Frontend Development of Escrow agreement page, escrow arbitration page, Moderating page

Milestone 7: Testing, Bug fixing and release version Alpha

	Objective 1: Testing of all units and functions
	
	Objective 2: Bug fixing respectively 
	
	Objective 3: Launching Alpha version 0.1

#### What is your Discord username?
SazidAhmed > SazidAhmed#8192

#### Additional files and documentation including architectural diagrams, wireframes, research documents, visuals, etc… (optional)
- Wireframes : https://drive.google.com/drive/folders/10bOXXDXiGLC0vSs-Mg9Kd8dW6cn3zK3V?usp=sharing
- UML Diagram : https://drive.google.com/drive/folders/1qBFPnMvBJmP4HZikM4hg3AAT17GOW56W?usp=sharing

# Milestone Details
Milestone 1: Authentication, profile and roles
		
	Objective 1: UI/UX Design
	 	Tasks: Page design of Website Home, User-Registration, Email-Confirmation, User-Signin, Password-Reset, User-Profile, user-profile-setting, admin-panel-layout , all-user-management, user-role-permission-management
	
	Objective 2: Server Development
		Tasks: Api development of User-Registration, Email-Confirmation, User-Signin, Password-Reset, view-user-profile, update-user-profile, user-password-change, CRUD methods for user-role-perrmission

	Objective 3: Management & Architecture
		Tasks: Wireframe and UML

#### Milestone Description
This milestone is to set the foundation of the application by building layouts of authentication, user profile structures and their respective roles.

#### Requested Payment Upon Completion
60,000 TNBC

| # | Objective           | Estimated Value (coins)   |
| - | ------------------- | ------------------------- |
| 1 | Objective 1: UI/UX Design              | 20,000 TNBC  | 
| 2 | Objective 2: Server Development        | 30,000 TNBC  |
| 3 | Objective 3: Management & Architecture | 10,000 TNBC  |

**Comment by manishram** [comment]
Hey @SazidAhmed, we liked your idea but there are lots of potential threats hidden in this project. And hence we are going to have a short meet with govs. before any final say on this.

**Comment by buckyroberts** [comment]
Hey @SazidAhmed, after meeting with the government we have unfortunately decided not to fund this project. This decision is based on 2 factors:
1. TNBC does not yet have the widespread adaption/network effect that would be required in order for this project to be successful
2. At this point in time we are focused on web based applications that do not require people to physically meet

**Comment by SazidAhmed** [comment]
I understand the factors and I support the decision of government.
Thank you.
