### ISSUE TITLE
Informative articles for thenewboston community

### ISSUE THREAD

**Issue by denistsoi** [thenewboston-developers/Projects#183]
# Project Details

May 2021:
- updated payouts due to core team reduction.

#### How would you describe your project?
I've noticed in the discord chat about topics enquiring about quite foundational information, e.g. where to find resources about crypto, project management, software engineering. Through those conversations, I'd like to not repeat myself, and start a series of articles that aim to educate the community about software engineering, project management, which serves as a reading portal. For some readers, there will be a donation section at the bottom of the page to the author.

#### What problem does this project solve?
After talking with various community members on the discord, having a central place for them to read about topics would help educate their knowledge.

#### Who is the target market?
Non-technical community members in thenewboston discord

#### How will this project benefit the network and/or the community?
Educate the community. (and through donations, increase tnbc velocity)

#### How is this project centered around thenewboston?
By sharing articles about say, project management or general crypto, it would increase the efficacy of projects
i.e. Rather than having a long conversation about where to find info, this can be a supplementary resource.

#### What is the estimated completion date for this project? (rough estimates are acceptable)

For the first milestone, I would use something like Notion as a writing platform to publish articles. - 
I'd say May 1st for the first series of articles.

#### Please include a detailed roadmap for your project below. This must include a list of all milestones where payments will be awarded upon completion of each.

| # | Objective           | Estimated Value (coins)   | Estimated Time |
| - | ------------------- | ------------------------- | --- |
| 1 | A Guide to Project Management | 8000 |  10 hours |
| 2 | How to structure your resumé + template | 4000 | 5 hours |
| 3 | A Beginners guide to Blockchain | 4000 | 5 hours |
| 4 | A guide to software engineering interviews (algorithms + sample code) | 16000 | 20 hours |
| 5 | An intro to NFTs (and explanation) | 4000 | 5 hours |
| 6 | A history of smart contracts (hopefully in time for beta) | 4000 | 5 hours |

#### What is your Discord username?
wakawaka (https://discord.gg/thenewboston)

#### Additional files and documentation including architectural diagrams, wireframes, research documents, visuals, etc… (optional)

For Phase 1:
I would use `Notion` as a way to publish articles that I've written.
I would expand these articles for phase 1 asking the community what they would like to read.

Example of other previously published articles/guides: 
- https://www.notion.so/denistsoi/Yields-Bonds-and-Asset-Prices-4052b9dbe64d45d495cc48b0b5d48d51
- https://www.notion.so/denistsoi/NFTs-cdf1f7d5412841be90902a6fe66de6b6
- https://twitter.com/DenisTsoi/status/1298574459779997696
- https://dtsoi.com/rg/

For Phase 2: 
when I've received enough we can investigate whether publishing on the official blog is necessary 
(and integrate a template for donations)

# Milestone Details

Please include a detailed breakdown of the first milestone including a list of all quantifiable objectives and 
estimated coin value of each. Upon completion of the milestone, each objective will be reviewed by thenewboston team 
and once all objectives have been verified as completed, coins will then be rewarded.

Note that all future detailed milestone breakdowns will be written as a separate GitHub issue. Only the first one is 
included in the project proposal.

---

#### Milestone Description

Finish publication of initial ideas for the community (noted below)

#### Requested Payment Upon Completion
16000

| # | Objective           | Estimated Value (coins)   | Estimated Time |
| - | ------------------- | ------------------------- | --- |
| 1 | A Guide to Project Management | 8000 |  10 hours |
| 2 | How to structure your resumé + template | 4000 | 5 hours |
| 3 | A Beginners guide to Blockchain | 4000 | 5 hours |

**Comment by denistsoi** [comment]
@manishram also updated payout here as well.

**Comment by denistsoi** [comment]
Draft documents will be found here https://www.notion.so/wakawakatnbc/TNBC-Learning-Published-by-wakawaka-73ffbe1715bf4005bfeabeb64a43b184

Project management will be complete tomorrow

https://www.notion.so/wakawakatnbc/Guide-to-Project-Management-bfcea64080c344d48d324711e9bbf6f0

**Comment by manishram** [comment]
Hey @denistsoi, we reviewed your proposal. We are going to meet with govs. to get final say on this.

**Comment by buckyroberts** [comment]
Hey @denistsoi, after meeting with the governors we have decided not to fund this project for the following reasons:
- TNB does not yet have an official blog where we would be able to post these articles
- When TNB  does have a blog (in the near future), our article funding will be paid based on bounties rather than projects
- For any articles funded that are published on platforms outside an official TNB blog, all of those articles would have to be related directly to TNBC
