### ISSUE TITLE
tnBabel

### ISSUE THREAD

**Issue by AbhayAysola** [thenewboston-developers/Projects#185]
# Project Details

#### How would you describe your project?
A project which focuses on making TNB more accessible to developers who work in different stacks by creating libraries in various languages to interact with the TNB network.

#### What problem does this project solve?
Currently, the only way to interact with the network through code is to use the JS SDK. This is not ideal since many apps and projects are being developed in a variety of languages such as Python, Golang, C++ and more. 

#### Who is the target market?
The target market are developers interested in interfacing with the chain.

#### How will this project benefit the network and/or the community?
This project will benefit the network greatly by creating more avenues and entrypoints for new devs to just import the libraries and start coding, instead of having to figure out the encryption and signing behind the chain.

#### How is this project centered around thenewboston?
This project will be building tools and libraries which interface with thenewboston blockchain.

#### What is the estimated completion date for this project? (rough estimates are acceptable)
Mid May - End of May

#### Please include a detailed roadmap for your project below. This must include a list of all milestones where payments will be awarded upon completion of each.
* Golang Implementation
    * Account
        * Tests
        * Documentation
    * Node
        * Tests
        * Documentation
    * Others (Voting, Governance, Lockup Coins)

* Python Implementation
    * Account
        * Tests
        * Documentation
    * Node
        * Tests
        * Documentation
    * Others (Voting, Governance, Lockup Coins)

* C++ Implementation
    * Account
        * Tests
        * Documentation
    * Node
        * Tests
        * Documentation
    * Others (Voting, Governance, Lockup Coins)

* Other languages (Based on community choice)

Completion of each language milestone will be based on addition to their respective package registry (pypi.org for Python, pkg.go.dev for Golang, etc.)

#### What is your Discord username?
Abhay#6969

# Milestone Details

Please include a detailed breakdown of the first milestone including a list of all quantifiable objectives and 
estimated coin value of each. Upon completion of the milestone, each objective will be reviewed by thenewboston team 
and once all objectives have been verified as completed, coins will then be rewarded.

Note that all future detailed milestone breakdowns will be written as a separate GitHub issue. Only the first one is 
included in the project proposal.

---

#### Milestone Description
Write a complete Golang Module to be used to interface with thenewboston blockchain. Write tests and documentation for the same.

#### Requested Payment Upon Completion
70000

| # | Objective           | Estimated Value (coins)   |
| - | ------------------- | ------------------------- |
| 1 | Golang Implementation | 40000 |
| 2 | Tests for Golang Implementation | 20000 |
| 3 | Documentation for Golang Implementation | 10000 |

**Comment by angle943** [comment]
Hello @AbhayAysola , after reviewing your project proposal, we like the idea, but we would like for you to narrow the scope of the project. Each SDK language can be a separate project. It looks like you want to to start with Golang, so this can be considered a Golang SDK project if that where you want to begin.

Once you have chosen a language you want to begin with, we also advise the milestones be more broken up into smaller chunks, instead of having one broad milestone. here is an example of an sdk project broken up more granular: https://github.com/thenewboston-developers/Projects/issues/176

**Comment by AbhayAysola** [comment]
> Hello @AbhayAysola , after reviewing your project proposal, we like the idea, but we would like for you to narrow the scope of the project. Each SDK language can be a separate project. It looks like you want to to start with Golang, so this can be considered a Golang SDK project if that where you want to begin.
> 
> Once you have chosen a language you want to begin with, we also advise the milestones be more broken up into smaller chunks, instead of having one broad milestone. here is an example of an sdk project broken up more granular: #176

Okay that seems fair I will close this issue and redo it.
