### ISSUE TITLE
Digital Art buying and selling APP - Milestone 2,3,4,5

### ISSUE THREAD

**Issue by gautamkmahato** [thenewboston-developers/Projects#188]
#### Link to the original project proposal.
[https://github.com/thenewboston-developer/Projects/issues/177](https://github.com/thenewboston-developers/Projects/issues/177)

#### Link to most recent milestone payout request.
[https://github.com/gautamkmahato/Digital-art-marketplace/tree/master](https://github.com/gautamkmahato/Digital-art-marketplace/tree/master)

#### Milestone Description
Milestone 1 will be the design of the website layout and the frontend. In Milestone 2 the Front-end to be done and starting of backend architecture and design. In Milestone 3 we will be adding some extra features to the website. In Milestone 4 Back-end to be done and in Milestone 5 Testing and deployment will be done.

#### Requested Payment Upon Completion
Objective 1: 30th April 2021
complete the website design
completion of the frontend part like the design of the website layout, login/signup, creating the profile, uploading, images, navigation, landing page, dashboard, profile, etc.

ESTIMATED_AMOUNT_OF_COINS - 15,000 coins

Objective 2: 1st  June 2021
Backend architecture and designs
complete the basic backend functionality of the website like login/signup, creating the profile, uploading, displaying images category-wise.
creating a database and connecting it with the backend etc.

ESTIMATED_AMOUNT_OF_COINS - 25,000 coins

Objective 3: 5th July 2021
Adding additional features like biding functionality, payment service.
integration of blockchain/ TNB coin, etc.
Completion of Frontend and Backend

ESTIMATED_AMOUNT_OF_COINS - 35,000 coins

Objective 4: 15th August 2021
adding some extra features to the websites
Completion of Frontend and Backend

ESTIMATED_AMOUNT_OF_COINS - 40,000 coins

Objective 5: 15th  September 2021

Testing
deploying the website.

ESTIMATED_AMOUNT_OF_COINS - 45,000 coins

#### Project Reviewer
NAME OF PROJECT REVIEWER HERE

#### Project Wallet
fc8e5f6209a1861e3456ccec70a83217e01c036df9dc8c005e636f9f1c0beb2a

**Comment by manishram** [comment]
Closing this for now because this milestone proposal is related to this project: https://github.com/thenewboston-developers/Projects/issues/177
