### ISSUE TITLE
Personal Vaccination Vault/Passport

### ISSUE THREAD

**Issue by vizyourdata** [thenewboston-developers/Projects#189]
# Project Details

#### How would you describe your project?
A historical ledger of all vaccines an individual has received. Users can access their history and share records with anyone requesting proof. The administering entity (medical providers) would create the record of vaccination. Medical entities would be validated/certified in the network so that governments/schools can rely on the records. Records would be used as proof of vaccination for travel or school enrollment where vaccines are required.

#### What problem does this project solve?
As more and more countries are requiring test results and or vaccine proof before visitors enter, this would provide a valid single source of truth for individual vaccine history. 

The application is not just limited to the current pandemic but to lifelong vaccination history. Has anyone else here had to scramble to find kids' vaccine records to enroll them in school or when changing schools? If parents have lost track of this, its quite possible they have to go to multiple medical providers to get a complete record. This would keep all of those validated/verifiable records securely in one place.

I just stepped on a rusty nail, did I get that Tetanus vaccine 8 years ago or 12? Check the history to verify if a booster is needed.
Another feature would be to alert individuals when their vaccination is expiring.

#### Who is the target market?
Vaccinated Individuals
Business/Recreational Travelers
Parents/Families
Medical Practitioners - record of their patients' vaccinations shared to individuals through the app
Governments that want to track their vaccination rates and those who are requiring proof of vaccination from their citizens

#### How will this project benefit the network and/or the community?
Providing a very timely service to our communities/countries for safe travel and for anyone tracking personal or citizen vaccinations.

#### How is this project centered around thenewboston?
Providing a large population of users that would rely on the tnb blockchain for verifiable records. 

#### What is the estimated completion date for this project? (rough estimates are acceptable)
ANSWER HERE

#### Please include a detailed roadmap for your project below. This must include a list of all milestones where payments will be awarded upon completion of each.
ANSWER HERE

#### What is your Discord username?
vizyourdata#3945

#### Additional files and documentation including architectural diagrams, wireframes, research documents, visuals, etc… (optional)
- OPTIONAL ATTACHMENT HERE
- OPTIONAL ATTACHMENT HERE
- OPTIONAL ATTACHMENT HERE

# Milestone Details

Please include a detailed breakdown of the first milestone including a list of all quantifiable objectives and 
estimated coin value of each. Upon completion of the milestone, each objective will be reviewed by thenewboston team 
and once all objectives have been verified as completed, coins will then be rewarded.

Note that all future detailed milestone breakdowns will be written as a separate GitHub issue. Only the first one is 
included in the project proposal.

---

#### Milestone Description
SHORT DESCRIPTION OF MILESTONE HERE

#### Requested Payment Upon Completion
AMOUNT OF COINS HERE, ESTIMATED COIN VALUES DOES NOT NEED TO BE FILLED OUT UNTIL YOU MEET WITH A PROJECT REVIEWER

| # | Objective           | Estimated Value (coins)   |
| - | ------------------- | ------------------------- |
| 1 | Example objective A | ESTIMATED_AMOUNT_OF_COINS |
| 2 | Example objective B | ESTIMATED_AMOUNT_OF_COINS |
| 3 | Example objective C | ESTIMATED_AMOUNT_OF_COINS |

#### Project Wallet
will update

**Comment by manishram** [comment]
Hey @vizyourdata please update your project roadmap, milestone details, and estimated completion date.

**Comment by kristykjlee** [comment]
@vizyourdata This is a great idea, however it is not centered around TNBC, so the project will be rejected.
