### ISSUE TITLE
On-chain Social Network [draft]

### ISSUE THREAD

**Issue by Kycermann** [thenewboston-developers/Projects#191]
# Project Details

#### How would you describe your project?
Censorship free social network that stores posts on chain.

#### What problem does this project solve?
Censorship, centralised controlled social media, targeted ads, etc.

#### Who is the target market?
Everyone :)

#### How will this project benefit the network and/or the community?
Our own social network, powered by the chain!

#### How is this project centered around thenewboston?
The social network is powered by the chain.

#### What is the estimated completion date for this project? (rough estimates are acceptable)
August 1st

##### Chain scanner
Create open source chain scanner that fetches posts from memos and provides a public API to easily view posts.
Posting messages will work via empty feeless memo transactions to a TNBC address ("channel").

##### Web client
Create an open source web client (website) to access the social network via the API.

##### Private messages
Private messages will be posted to the receiver's TNBC address and encrypted with the receiver's public key.

##### Public channels
All TNBC addresses are public channels. The network will have a default address but people will be able to add others. 

##### Usernames
Usernames come from TNB usernames. Channels can require posters to have a TNB username.

##### Moderation
A minority of users will abuse the decentralised censorship-free nature of this project to post hate etc. Each channel owner (holder of the signing key) will be able to block addresses from posting to the channel. This will be done by filtering their content at the Chain Scanner level.

##### Later
Once the MVP is done, we'll add:
1. Direct Messages (by encrypting messages posted to a channel)
2. Images files by storing hashes on-chain
3. More ways for channel owners to customise channels (rather than just name & requireUsernameToPost)
4. Mobile app
5. Group chats

#### What is your Discord username?
Pixel#2473 (https://discord.gg/thenewboston)

# Milestone Details

Please include a detailed breakdown of the first milestone including a list of all quantifiable objectives and 
estimated coin value of each. Upon completion of the milestone, each objective will be reviewed by thenewboston team 
and once all objectives have been verified as completed, coins will then be rewarded.

Note that all future detailed milestone breakdowns will be written as a separate GitHub issue. Only the first one is 
included in the project proposal.

---

#### Milestone Description
Backend MVP

The Chain Reducer will scan & reduce all the data on the chain to the social network data- to provide the social network data via an HTTP API. Anyone can run a Chain Reducer and anyone can use any Chain Reducer.

Once this is complete, the network will be funtionally usable if you're happy to not have a frontend!

#### Requested Payment Upon Completion

| # | Objective           | Estimated Value (coins)   |
| - | ------------------- | ------------------------- |
| 1 | Scan the chain in real-time / catch up after downtime / 100% consistency | . |
| 2 | Memo reducer (backend): messages, settings, moderation, popular channels & hashtags | . |
| 3 | Persistent data store from reducer | . |
| 4 | Public API to access reduced chain data, filtering by channel(s), author(s) | . |

#### Milestone Description
Frontend MVP

The Frontend uses a Chain Reducer API to fetch social network data, and submits new transactions to post to the social network.

#### Requested Payment Upon Completion

| # | Objective           | Estimated Value (coins)   |
| - | ------------------- | ------------------------- |
| 1 | Create Twitter-like social media website design | . |
| 2 | Sidebar: popular channels / hashtags | . |
| 3 | Main bar: posts with unlimited scrolling | . |
| 4 | Client side "Follow Author" and "Follow Channel" | . |
| 5 | View list of authors and channels following
| 6 | Personal channel page (view posts in channel) | . |
| 7 | Block, unblock authors from personal channels & view blocked authors | . |

#### Project Reviewer
Preferred: Manish

#### Project Wallet
add7f7dc1f719179530f7e6c39cb70b2dd671119b63159e1383b190912b8e1c7

**Comment by buckyroberts** [comment]
@Kycermann we like this idea, however our blockchain architecture can not yet support this type of application given that it would require a rewrite of the core protocol to be able to store this type of data.
