### ISSUE TITLE
TNB Donation

### ISSUE THREAD

**Issue by Toledit** [thenewboston-developers/Projects#193]
# Project Details

#### How would you describe your project?
> Came across an idea-only submission that is fairly similar to our project. Therefore this issue Closes #4

A networking solution that used to help your favorite creator and support open-source projects by donating TNB coins directly to them from a browser extension.

#### What problem does this project solve?
TNB Donation enables the community to support each other on the blockchain.
The project also helps in distributing TNB coins to the people at large.

#### Who is the target market?
All coin holders who are on social media or software development platforms like GitHub and Npm.

#### How will this project benefit the network and/or the community?
By using thenewboston currency to support your favorite projects (on Github) and content creators (on Youtube) which keeps the community stays motivated, It also helps distribute the coins further and increase adaptability which helps the network in a major way while empowering the projects supported.

#### How is this project centered around thenewboston?
As we know thenewboston is a community that started its journey on youtube with the goal of giving free access to all sorts of skills to the community as also is at this moment. And supporting these creators is undeniably essential to improve the content's overall quality. 

#### What is the estimated completion date for this project? (rough estimates are acceptable)
End June of 2021 if approved early.

#### Please include a detailed roadmap for your project below. This must include a list of all milestones where payments will be awarded upon completion of each.
[Roadmap](https://docs.google.com/spreadsheets/d/1PgR-fRlBJYbyLVHWHP5dZf8T9nsrWTqfBhmdp9sX3QU/edit?usp=sharing)
| # | Milestones           | Estimated Value (coins)   |
| - | -------------------- | ------------------------- |
| 1 | Project initialization | - |
| 2 | Prototype UI/UX | - |
| 3 | Frontend Implementation | - |
| 4 | Backend Implementation | - |
| 5 | Deploying | - |
| 6 | QA & overall testing | - |

#### What is your Discord username?
7oledit#8388

#### Additional files and documentation including architectural diagrams, wireframes, research documents, visuals, etc… ![TNBdonation Architecture](https://user-images.githubusercontent.com/27518021/115001264-2e1abd80-9eac-11eb-990f-e5cf4fd739b4.png)

# Milestone Details

Please include a detailed breakdown of the first milestone including a list of all quantifiable objectives and 
the estimated coin value of each. Upon completion of the milestone, each objective will be reviewed by thenewboston team and once all objectives have been verified as completed, coins will then be rewarded.

Note that all future detailed milestone breakdowns will be written as a separate GitHub issue. Only the first one is 
included in the project proposal.

---

#### Milestone Description
The first milestone is Project initialization.
In this project development stage, we finalize everything needed for getting started.

#### Requested Payment Upon Completion
--

| # | Objective           | Estimated Value (coins)   |
| - | ------------------- | ------------------------- |
| 1 | Create GitHub repo, Socials & Branding | - |
| 2 | Define project scope & architecture | - |
| 3 | Generate project roadmap | - |

#### Project Reviewer
YOU CAN EITHER WRITE YOUR PREFERRED PROJECT REVIEWER HERE, OR LEAVE IT EMPTY FOR ANY PROJECT REVIEWER TO PICK THIS PROJECT UP.
EX - `Preferred: John Doe`

#### Project Wallet
449baf4c0b43f44e9b091947bf36880bf237a91e413adb85ca2ae1f33e239440

**Comment by mrbusysky** [comment]
Keysign already does this and it's actively already in browsers.

https://github.com/Keysign-Wallet/keysign/blob/master/DOCS.md#requesttransfer

**Comment by javina89** [comment]
Hey @Toledit , while copies of another project are not allowed, competition is. Can you let me know how this differs from Keysign-Wallet?

**Comment by Toledit** [comment]
Hello Chuy, so I had some time to look at keysign. I don't even think our project is competitive let alone being a copy of keysign since it's trying to solve entirely different issue.

Our vision is create a platform that enables the comunity donate TNB coins to content creators and opensource contributors and projects. 

Unlike keysign, Our sole purpose is not to create an extension wallet to TNB coin platform, but to create a donation platform where creators and open-source projects get support and track their donation status on PWA. As shown on our architecture picture in the proposal above, Our main platform is going to be a PWA. The extention's only purpose is to ease the use of our main PWA and communicate with it.

The only similarity i see we have with keysign is that we also utilize a browser extension for convenience as hundreds of thousands distinct applications do.

**Comment by kevinnim1990** [comment]
I'd like to point out almost none of this was in the 

> 
> 
> Hello Chuy, so I had some time to look at keysign. I don't even think our project is competitive let alone being a copy of keysign since it's trying to solve entirely different issue.
> 
> Our vision is create a platform that enables the comunity donate TNB coins to content creators and opensource contributors and projects.
> 
> Unlike keysign, Our sole purpose is not to create an extension wallet to TNB coin platform, but to create a donation platform where creators and open-source projects get support and track their donation status on PWA. As shown on our architecture picture in the proposal above, Our main platform is going to be a PWA. The extention's only purpose is to ease the use of our main PWA and communicate with it.
> 
> The only similarity i see we have with keysign is that we also utilize a browser extension for convenience as hundreds of thousands distinct applications do.

I'd like to point out none of this was in the main post.

Also, this project is useless everything they are proposing can already be done on the chain for free. All they are doing is trying to centralize data. All these creators need is a wallet address. They can be paid and track those donations easily. Keysign literally sorts this information by month and can be updated to do weekly and daily. Their extension would literally be a clone of keysign so why wouldn't they just integrate keysign.

The website and storing free data is the only thing different, They would literally be creating the same extension just with a few differences. If anything should be paid to be made it would be the website only because it's the only thing different here. Also what they are proposing is a product that is from an over-saturated market. It would be cheaper to convince a big well-known company to accept tnbc.

**Comment by exeligent** [comment]
I hope kevinnim1990 understands the difference between wallets and donations. Let me give you an insight. We are building a donation platform (not an EXTENTION) on top of the TNB coin. The donation is performed with our PWA platform. The extension is not of TNBs but our donation web app. 

Let's see some real-world scenario: A person can donate on goFundMe with PayPal. A person can also send the money to the campaign creator directly with Paypal. GoFundMe made the donation process easier. This doesn't mean GoFundMe is a clone of PayPal's. Is it? GoFundMe can have an extension, so does PayPal. 

to clarify in detail. I've used the following reference :
 GoFundMe --------> our TNB donation platform
PayPal         --------->   TNB 
PayPal's extension ----> keysign

**Comment by exeligent** [comment]
Hey Chuy, Our main vision is to encourage content creators and open-source projects. We have seen and admired a lot of open-source projects, videos, and answers to our challenging questions. We are creating a platform for the community to contribute to free content that they found useful; providing an additional and powerful option other than a like button, a star, or an up-vote. Our purpose is to encourage open-source contributors and content creators. Which I believe is also a value that TNB shares.

**Comment by buckyroberts** [comment]
Hey @Toledit, a few questions about the proposal:
- Are you planning to make a website as well?
- If so, would you mind providing some sample wireframes and a basic sitemap?
- Lastly, regarding the project milestones, these will need to be quantifiable proof of work which auditors will be able to verify. Objectives such as recruitment are not considered "quantifiable proof of work".

**Comment by Toledit** [comment]
Thanks for getting back to us!
1. Yes, we'll have a progressive web app.
2. Sitemap: *apologies for low quality there https://drive.google.com/file/d/1DU74KA0jzeaQTg0CFfyXtIfaMVei7p_l/view?usp=sharing
some prototypes of the pwa: 
User profile
![User2](https://user-images.githubusercontent.com/27518021/119352525-75198100-bcaa-11eb-917e-117b21fffd9e.png)
Browse users:
![User](https://user-images.githubusercontent.com/27518021/119352569-83679d00-bcaa-11eb-89fc-3ed73c34c856.png)
Admin dashboard:
![Admin](https://user-images.githubusercontent.com/27518021/119352592-8ebac880-bcaa-11eb-8754-edddf6c7c44c.png)
*Tentative! features might be modified slightly in the future.
3. Edited the proposal document above as suggested.
Thanks.

**Comment by angle943** [comment]
Hello @Toledit , we approve of this project and your first milestone!

Based upon your limited information of your milestone objectives, we decided to skip `objective 3`, as we see that you have already created your roadmap (the first table on your project proposal).

Therefore, from what we can deduce from objective 1 and 2, we felt that the amount of 5000 coins is appropriate for milestone 1

**Comment by Toledit** [comment]
> Hello @Toledit , we approve of this project and your first milestone!
> 
> Based upon your limited information of your milestone objectives, we decided to skip `objective 3`, as we see that you have already created your roadmap (the first table on your project proposal).
> 
> Therefore, from what we can deduce from objective 1 and 2, we felt that the amount of 5000 coins is appropriate for milestone 1

Thanks for the Approval, we waited for a while but it's finally here.  
I am not sure if skipping objective is a good idea. As there's a lot of work put on to it by my team and I now have to tell them it was for free? Let me know your thoughts.
Thanks again!!

**Comment by angle943** [comment]
Hi @Toledit , roadmaps are typically part of the project proposal, and are not accounted for in the project evaluation itself.

Roadmaps are part of the project proposal such that the auditors can accurately assess the value. We do not pay for management, meetings, planning, but rather for quantifiable value that you can provide to us and the community.
