### ISSUE TITLE
Machine Learning on TNB for Healthcare

### ISSUE THREAD

**Issue by Mirch** [thenewboston-developers/Projects#194]
# Project Details

#### How would you describe your project?
This is a research/MVP development project that I am building as part of my Master's thesis. The aim of the project is to use the TNB blockchain as the infrastructure and data source for a Machine Learning model in the healthcare field. 

#### What problem does this project solve?
In the context of TNB:
- hosting personal data on the blockchain and owning it
- running other applications (the ML model) on TNB
In the context of healthcare:
- democratizing patient data 
- allowing users to use their medical data as they please (including selling it)
- allowing users to take their medical data with them across borders

#### Who is the target market?
People who want to own their medical data, have it all in one place and be able to take it with them across the globe.

#### How will this project benefit the network and/or the community?
The project will act as a guideline for how to implement similar ideas on the TNB blockchain.

#### How is this project centered around thenewboston?
The infrastructure will run on the TNB blockchain.

#### What is the estimated completion date for this project? (rough estimates are acceptable)
It should be finished by July/August.

#### Please include a detailed roadmap for your project below. This must include a list of all milestones where payments will be awarded upon completion of each.
Milestone 1: Adding the necessary changes to the nodes and deploying them to AWS (for testing purposes and in order to not interfere with the "main" blockchain)
Milestone 2: Generating data and adding it to the mock blockchain
Milestone 3: Building, training and testing the ML model
Milestone 4: Interpreting the results

#### What is your Discord username?
Mircea Oprea#8141

#### Additional files and documentation including architectural diagrams, wireframes, research documents, visuals, etc… (optional)
To be done :) 

# Milestone Details

The first milestone consists of enhancing the blockchain to allow users to upload JSON data, deploy a few nodes to AWS and test the whole system by making a separate application (probably a small console app) that would interact with the nodes' API. 
Estimate: 3500 TNBC 

---

#### Milestone Description
The first milestone consists of enhancing the blockchain to allow users to upload JSON data, deploy a few nodes to AWS and test the whole system by making a separate application (probably a small console app) that would interact with the nodes' API. 

#### Requested Payment Upon Completion

| # | Objective           | Estimated Value (coins)   |
| - | ------------------- | ------------------------- |
| 1 | Finshing the network changes | 0 |
| 2 | Deploying the nodes | 0 |
| 3 | Testing the network | 3500 |

#### Project Wallet
aa93d767360d05ab279482d5c7b7ac3e016f3cc0362a40c0a4b5c087b80958ed

**Comment by buckyroberts** [comment]
@Mirch unfortunately we are unable to fund projects that require altering the core architecture or protocol of the TNB blockchain.
