### ISSUE TITLE
Restaurants Self-Order - Milestone - 1

### ISSUE THREAD

**Issue by yaya-BL** [thenewboston-developers/Projects#199]
#### Link to original project proposal.
https://github.com/thenewboston-developers/Projects/issues/26

#### Link to most recent milestone payout request.
We don't have any recent milestone payout request.

#### Milestone Description
To have a glance back on the app's architecture, with enriching our documentation, and complete the mobile app UI design

Objective 1 : System Architecture & Design
       Tasks: 

              1. Wireframes of Internal Portal,
              2. Business Rules of Internal Portal,
              3. UML of Internal Portal
              4. Database Design
              5. Documentation of each modules

Objective 2: UI Design of Employee mobile view
       Tasks: Designing UI for the pages given below

              1. Dashboard ( Today's order, pending orders )
              2. list of completed order ( filter by today's order, all orders )
              3. detailed view of an specific completed order with all the items with price related to this order, total payment, date and customer details ( contact, pickup address )
              4. list of incomplete orders ( there will the status for each order : "on-process", "ready for pickup" , "completed")
              5. from order list once click on a specific order, it will show the order date and time, order processing time, the order items with price, note (if any), sub total and total price along with customer details ( contact, pickup address )
              6. list of "ready for pickup" orders
              7. list of completed orders for today
              8. Enhancing and finishing up the comments of mobile app customer view

Objective 3 : Team Lead and Management
       Tasks: 

              1. Maintaining the project 
              2. Regular interaction with team members 
              3. Meeting with team members
              4. Milestone proposal
              5. open github project with all the task related to each objective

Objective 4 : Software documentation
       Tasks: Write Documentation for 

              1. Backend Apis documentation with Swagger
              2. Functional description of Internal portal
              3. Product requirements    

#### Requested Payment Upon Completion
60,000 TNBC

| Objective                                            | How can auditors verify milestone? |
| -------------------------------------------------| ------------------ |
| System Architecture & Design           | Will provide the document |
| UI Design of Vendor mobile view       |Figma links will be available  |
| Team Lead and Management            | - |
| Software Documentation                   | Will provide the document |

#### How long do you estimate this milestone will take to complete?
~4 Weeks

#### Project Reviewer
Manish#4379

#### Project Lead Discord ID
Yahya#2796

#### Project Wallet
df647df0271bae12661b61af74076579fc67db288118ba95c5c9237b3a76d083

**Comment by manishram** [comment]
Hey @itsnikhil, we are going to have a meeting with govs regarding the standard method to calculate the number of coins for milestones.

**Comment by manishram** [comment]
Hey @yaya-BL your 3rd objective `Team Lead and Management` for this milestone is not quantifiable and we are paying for that.
Rest all looks good. Can you please update it and then I'll label it for final review by govs.

**Comment by yaya-BL** [comment]
Hello @manishram 
"Team Lead and Management" has been removed from the estimates

**Comment by angle943** [comment]
milestone 1 approved for 60000 coins!

**Comment by tspearing** [comment]
@yaya-BL, please add your discord username including number.
