### ISSUE TITLE
tnbCrow- Milestone - 1

### ISSUE THREAD

**Issue by hussu010** [thenewboston-developers/Projects#200]
#### Link to the original project proposal.
https://github.com/thenewboston-developers/Projects/issues/129

#### Link to most recent milestone payout request.
Null

#### Detailed application architecture, user flow, and stories. 
- Document every condition of trade cycle: https://github.com/tnbCrow/Backend/issues/59
- Documented detail User Flow: https://github.com/tnbCrow/Management/issues/14
- Write detailed User Stories: https://github.com/tnbCrow/Management/issues/13. 
- Generate OpenAPI documentation
- Debug toolbar for database optimization

Coins: 30k

#### `trade-post` API endpoint tasks
- Finalize the database model according to the updated user flow and stories
- Validates if the seller has enough balance before creating the trade post
- Locks seller's coins after trade post are created
- Only authenticated user can create the post
- Only the owner of the trade post can edit the trade post
- Owner can load extra coins into the trade post
- Owner can withdraw coins from the trade post
- trade post will be created including the fees for the seller
- fees will be refunded when withdrawing coins from the trade post
- checks if the user has enough balance before loading the coins or creating trade post
- transaction fees could be edited through the admin portal, do not lock coins for buyers. 

Coins: 40k

#### `trade-request` API endpoint tasks
- Finalize the database model according to the updated user flow and stories
- the user will be able to send a trade request to the post owner
- only the owner or initiator can view the trade request
- if the user wants to sell coins; they need to have coins loaded with fees
- amount of coins request cannot exceed the post amount
- fees calculated with seller sends trade request
- the user with the ability to accept/ reject/ cancel trade request
- trade-request expired if no action within a day
- unlock coins back if trade request expired/ rejected or canceled with fees
- separate permissions for the separate status of trade-requests
- if trade-request accepted; move the buyer + seller to an active trade
- permissions on already updated trade-request. 

Coins: 40k

#### `active-trades` API endpoint tasks
- Finalize the database model according to the updated user flow and stories
- only the initiator and post owner can take part in active trade
- real-time chat functionality
- correct permissions can only change the status of active trade
- checks if payment windows expired before letting the seller cancel the trade
- our moderator can join in chat if a dispute created
- admin can change the status to canceled or completed
- once both parties confirm payment; update the balance of the buyer
- create an entry in the CompletedTrade model.

Coins: 50k

#### MVP site backend tasks
- Architect the backend structure of the MVP site.
- Implement the models and CRU of completed trades data.
- Automate the updating of the Statistics table with completed trades data.
- CRUD to blacklisted accounts that lists the accounts connected to scammers.
- API endpoint to return the Statistics to be used in discord bot.
- Deploy the site.

Coins: 50k

#### Design Tasks
- Complete the design of the MVP site. Coins: 8k
- Logo of tnbCrow. Coins: 10k
- Create OG images for social sharing and social media banners. Coins: 5k
- Drafting/sketching product specifications for core pages in the user flow. Coins: 5k
- Create user flow for the web and mobile experience. Coins: 10k
- Design the wireframe for each component in the proposed user flow for both platforms. Coins: 25k

Coins: 63k

#### Frontend Tasks
- Develop the FE of MVP according to the design.
- Integrate the FE with Django templates.

Coins: 25k

#### Requested Payment Upon Completion
298,000

| Objective           | Estimated Value (coins)   |
| ------------------- | ------------------------- |
| Detailed application architecture, user flow, and stories | 30,000 |
| `trade-post` API endpoint tasks | 40,000 |
| `trade-request` API endpoint tasks | 40,000 |
| `active-trades` API endpoint tasks | 50,000 |
| MVP site Backend tasks | 50,000 |
| Design Tasks | 63,000 |
| Frontend Tasks | 25,000 |

#### Project Wallet
79c0d308e31b9c4cf0f2bdaae65e2d8476c355084035ee11755facaa9597ff98

**Comment by manishram** [comment]
Hey @hussu010, we are going to have a meeting with govs regarding the standard method to calculate the number of coins for milestones.
