### ISSUE TITLE
TNB Mobile App

### ISSUE THREAD

**Issue by zinoadidi** [thenewboston-developers/Projects#204]
# Project Details

#### How would you describe your project?
Mobile application for TNBC. It will supplement the account manager on devices which current account manager cannot be deployed to. The Mobile app will provide users with all chain-related functionalities such as account management, transactions, and beta functionalities when they are available.

#### What problem does this project solve?
Lack of wallet for mobile users as well as lack of a way to interact with the chain from mobile devices

#### Who is the target market?
Anyone that is interested in owning tnbc or transacting with the chain

#### How will this project benefit the network and/or the community?
Allows more people to hold and use TNBC for daily transactions

#### How is this project centered around thenewboston?
The mobile app provides a way for end users to interact with the chain. With the mobile app, users can send, receive tnbc and perform other activities related to thenewboston chain

#### What is the estimated completion date for this project? (rough estimates are acceptable)
MVP ALPHA - 60 days.

#### Please include a detailed roadmap for your project below. This must include a list of all milestones where payments will be awarded upon completion of each.

| # | Roadmap Name | Duration Estimate   |
| - | ------------------- | ------------------------- |
|1| Project setup | 3 Days |
|2| Account (CRUD) UI & Integration | Two weeks |
|3| Transactions (CRUD) UI & Integration | Two weeks |
|4| Settings, configuration, security | One week |
|5| v1 release to stores and download centers | 3 days |
|6| Beta Functionalities | 6 - 8 Weeks |

#### What is your Discord username?
Zinoadidi
(https://discord.gg/thenewboston)

#### Additional files and documentation including architectural diagrams, wireframes, research documents, visuals, etc… (optional)
- Designs are available here >>
https://www.figma.com/file/h6f3frXkqhEegiHdmQFhRR/Cryptocurrency-App

# Milestone Details

Please include a detailed breakdown of the first milestone including a list of all quantifiable objectives and 
estimated coin value of each. Upon completion of the milestone, each objective will be reviewed by thenewboston team 
and once all objectives have been verified as completed, coins will then be rewarded.

Note that all future detailed milestone breakdowns will be written as a separate GitHub issue. Only the first one is 
included in the project proposal.

---

#### Milestone Description
Project setup - We will finalize designs, kick-off development, recruit team members/contributors and set up build/deployment process surrounding the project.

#### Requested Payment Upon Completion
AMOUNT OF COINS HERE, ESTIMATED COIN VALUES DOES NOT NEED TO BE FILLED OUT UNTIL YOU MEET WITH A PROJECT REVIEWER

| # | Objective           | Estimated Value (coins)   |
| - | ------------------- | ------------------------- |
| 1 | Create / setup simple mobile app / workflow for team | 2 hours |
| 2 | Onboard first set of contributors | 3 hours |
| 3 | Basic automated build and deployment flow for app | 3 hours |

#### Project Reviewer
none

#### Project Wallet
4eb09ac18143f8690303e92368193e86f272cba86a659a4b8b75e6725e24d869

#### Proposed Hourly Rate
1000 TNBC / hour

**Comment by zinoadidi** [comment]
Project repository https://github.com/thenewboston-developers/thenewboston-mobile

**Comment by zinoadidi** [comment]
@manishram ready for review, more information on what it looks like can be found https://www.figma.com/file/h6f3frXkqhEegiHdmQFhRR/Cryptocurrency-App

The target platform at first will be android and iOS will come in after

**Comment by manishram** [comment]
Okay

**Comment by buckyroberts** [comment]
Closing this project - moving @zinoadidi to the frontend team so that we can get development underway.
