### ISSUE TITLE
Blockchain Explorer- Milestone 1

### ISSUE THREAD

**Issue by itsnikhil** [thenewboston-developers/Projects#205]
# [Openblockchain Explorer](https://github.com/open-blockchain-explorer)

### Tasks:
- Ported stats page from tnb-analysis to explorer - https://tnbexplorer.com/tnb/stats
- Integrated live primary validator and bank APIs at various places - https://tnbexplorer.com/tnb/transactions
- Individual account page design - https://www.figma.com/file/LkDMK3NvpVbQjQF45qFOuH/tnbexplorer.com?node-id=54%3A2
- Individual account page code - https://tnbexplorer.com/tnb/account/5ad13fd8cc674da7a3ad35426e0fcfe3a3157a044ebda0f54b9b32ee873ea921/
- Trace transactions implementation in code - https://tnbexplorer.com/tnb/account/5ad13fd8cc674da7a3ad35426e0fcfe3a3157a044ebda0f54b9b32ee873ea921/trace-transactions
- Hired a designer for mobile view screen but the work was not satisfactory - https://www.figma.com/file/XdHCqKeNdP3IyOHvaIWkCz/mobile-page-for-TNBEXPLORER?node-id=0%3A1
- Experimented with visualizations via tableau - https://vizyourdata.github.io/javascriptAPI_demo.html
- Skill-up of the team in django and react especially towards websockets - https://testdriven.io/courses/taxi-react/
- Other discussions on discord and management related work

|Objective|Coins|Time spent|
|-|-|-|
|Mobile screens designs|30000|~1 week|
|Javascript based interactive charts in stats page|60000|~2 weeks|
|Live primary validator and bank APIs at various places|40000|~1 week|
|Individual account page|50000|~1 week|
|Tracing of transactions|10000|~2 days|
|Testnet & backend|30000|~1 week|
|Management|20000|-|
|**TOTAL**|**240000**||

### Project wallet address
1dfb0e7dd672032da0d8c29385ba6d22ec9d1134a115cc5596c5e4b69e6fc9a5

**Comment by manishram** [comment]
Hey @itsnikhil, we are going to have a meeting with govs regarding the standard method to calculate the number of coins for milestones.

**Comment by itsnikhil** [comment]
@manishram any update on this? it's been more than a week now

**Comment by manishram** [comment]
`Management` objective will not be considered.

**Comment by angle943** [comment]
Milestone 1 approved for 240,000 coins. If you wish to continue on with this project, please submit a milestone 2 proposal using this template! https://github.com/thenewboston-developers/Projects/issues/new?assignees=&labels=Milestone&template=milestone-proposal.md&title=NAME_OF_PROJECT+-+NAME_OF_MILESTONE+-+MILESTONE_NUMBER

**Comment by manishram** [comment]
Created a separate payout request issue for this milestone.
