### ISSUE TITLE
TNB Expense Tracker (Name TBA)

### ISSUE THREAD

**Issue by Niekon01** [thenewboston-developers/Projects#209]
# Project Details

#### How would you describe your project?
Money is extremely volatile. If not kept a proper record of, one can easily mismanage their funds, forget essential bills and payments, spend more than the required amount on unnecessary shopping, etc.

TNB Expense Tracker (Website/App) solves the problem of tracking these expenses for the user. Since TNB is more likely to become an everyday currency, the requirement to keep a track of the amount spent (or to be spent), bills paid (or to be paid), essentials bought (or to be bought), etc can definitely make life slightly easier for everyone.

#### What problem does this project solve?

- Keeping a track of monthly essential spending
- Keeping track of free-spending
- Helping users meet their saving goals
- Teaching people effective ways to make and save money
- Reminders for weekly and monthly payments
- Financial Calendar to track and manage expenses
- Using graphs for better visualization and facts about user's spending pattern 

#### Who is the target market?
The project's target market is

- normal users who are looking to make their life less frustrating by managing their expenses
- people looking to make the most out of their money
- project managers who have to hand out payments to people working for them
- freelancers who have earning goals
- businesses that have a manual earning/selling system

#### How will this project benefit the network and/or the community?

- It aims to provide project managers a way to track the money spent during the development of their projects
- It aims to provide the government a way to track the money released by the treasury (in case it is required to be tracked)
- The project aims to provide the people of the community a chance to earn TNBC
- In the long run, the project aims to provide the normal users a way to track their expenses when TNB becomes a part of the economy and infrastructure (daily usage coins)

#### How is this project centered around thenewboston?

The project will keep a track of TNB spending of users.

#### What is the estimated completion date for this project? (rough estimates are acceptable)
This project will only be started after the BETA version of TNB is releases. As I have never done a real development before, I am unsure how long this project may take.

#### Please include a detailed roadmap for your project below. This must include a list of all milestones where payments will be awarded upon completion of each.

-

#### What is your Discord username?
Niekon > Niekon#0116

#### Additional files and documentation including architectural diagrams, wireframes, research documents, visuals, etc… (optional)
- OPTIONAL ATTACHMENT HERE
- OPTIONAL ATTACHMENT HERE
- OPTIONAL ATTACHMENT HERE

# Milestone Details

Please include a detailed breakdown of the first milestone including a list of all quantifiable objectives and 
estimated coin value of each. Upon completion of the milestone, each objective will be reviewed by thenewboston team 
and once all objectives have been verified as completed, coins will then be rewarded.

Note that all future detailed milestone breakdowns will be written as a separate GitHub issue. Only the first one is 
included in the project proposal.

---

#### Milestone Description
SHORT DESCRIPTION OF MILESTONE HERE

#### Requested Payment Upon Completion
AMOUNT OF COINS HERE, ESTIMATED COIN VALUES DOES NOT NEED TO BE FILLED OUT UNTIL YOU MEET WITH A PROJECT REVIEWER

| # | Objective           | Estimated Value (coins)   |
| - | ------------------- | ------------------------- |
| 1 | Example objective A | ESTIMATED_AMOUNT_OF_COINS |
| 2 | Example objective B | ESTIMATED_AMOUNT_OF_COINS |
| 3 | Example objective C | ESTIMATED_AMOUNT_OF_COINS |

#### Project Wallet
PROJECT WALLET ACCOUNT NUMBER HERE

This project is half cooked as of yet. More details will be added as the idea grows and I am able to do a bit of research and talk to experienced people.

**Comment by angle943** [comment]
hello Niekon, we like the idea, but a couple questions.

1. Why do you need beta for this to be started?
2. Could you provide site-maps and basic wireframes of the website? 
3. Please fill out milestones in a way that is quantifiable and easily judged by the auditors

Closing this issue now, could you open up a new issue, and use the updated template to submit a new project proposal?

**Comment by Niekon01** [comment]
I am currently doing some research and brainstorming on what this project could look like. I simply posted the idea in case somebody else posted it first before me. I will open a new issue once I have all the requirements ready. Thanks!
