### ISSUE TITLE
tnbGo - tnb Account implementation in Golang - 1

### ISSUE THREAD

**Issue by AbhayAysola** [thenewboston-developers/Projects#213]
#### Link to the milestone and objectives table.
https://github.com/thenewboston-developers/Projects/issues/212

#### Detailed log of all completed objectives including valid proof of work.
https://github.com/AbhayAysola/tnb-go
All commits in this repo are related to this milestone

#### Project Wallet
81a1f1f5d167011f96a7e919997c5aca3f79f9389ba865901ab12c7ef1ade556

**Comment by manishram** [comment]
**Test Code:** `test.go`
```
package main

import (
	"github.com/AbhayAysola/tnb-go"
)
func main(){
print("Randomly generated keypair\n");
acc1, err := account.CreateAccount("")
if err != nil {
    panic(err)
}
print("SigningKeyHex:"+acc1.SigningKeyHex,"\n","AccountNumberHex:"+acc1.AccountNumberHex)
print("\n------------------------------------\n");

print("With signinkey passed in\n");
acc2, err := account.CreateAccount("74938d383000114b75f998f49d369dc98ffdb3bfef0f90744056e0165104b1ed")
if err != nil {
    panic(err)
}
print("SigninKey:"+acc2.SigningKeyHex,"\n","Acc #:"+acc2.AccountNumberHex)

print("\n------------------------------------\n");
print("CreateSignature\n");

acc, _ := account.CreateAccount("74938d383000114b75f998f49d369dc98ffdb3bfef0f90744056e0165104b1ed")
sig, err := acc.CreateSignature("hi")
if err != nil {
    panic(err)
}
print(sig+"\n")

print("\n------------------------------------\n");
print("Verify Signature\n");
sig1 := "7fdc1c0ece3d9c3cb74cf253ab7b339f1684352f33d50f3699884100e63a9c232d37a2ef8934d5dfa4dc4e28dc29ee05cb66c67db84032ad416bfd7929863b0d"
verified := account.VerifySignature(sig1, "20904d4790c907d507979f0c37f4c8c6d55533495c9c1963e8ec68351bc709d5")
print(verified)

print("\n------------------------------------\n");
print("Verify Key Pair\n");
matched := account.VerifyKeyPair("74938d383000114b75f998f49d369dc98ffdb3bfef0f90744056e0165104b1ed", "20904d4790c907d507979f0c37f4c8c6d55533495c9c1963e8ec68351bc709d5")
print(matched)
print("\n----------------END-----------------\n");
}
```
**Output:**

![3r434r3r3r](https://user-images.githubusercontent.com/22790904/119696207-95913900-be6c-11eb-9d04-3ed5aab12659.JPG)

---

**Audit**
- [ ] createAccount
- [ ] createSignature and verifySignature
- [ ] verifyKeyPair
- [ ] Tests
- [ ] Documentation

**Result:**
- Typo in Documentation (**[VerifyKeyPair](https://github.com/AbhayAysola/tnb-go/blob/main/DOCS.md#verifykeypair)**)

**Actually:**
```
matched := account.VerifySignature("signingKeyHex", "accountNumberHex")
print(matched)
// true or false
```

**Expected:**
```
matched := account.VerifyKeyPair("signingKeyHex", "accountNumberHex")
print(matched)
// true or false
```
Replace `VerifySignature` with `VerifyKeyPair`

**Comment by AbhayAysola** [comment]
> * Typo in Documentation (**[VerifyKeyPair](https://github.com/AbhayAysola/tnb-go/blob/main/DOCS.md#verifykeypair)**)
> 
> Replace `VerifySignature` with `VerifyKeyPair`
Whoops, my bad I'll fix that

**Comment by AbhayAysola** [comment]
Also, is this fine from an auditors point of view, or is there anything that I can do to make it easier?

**Comment by manishram** [comment]
@AbhayAysola it's fine.
