### ISSUE TITLE
tnbuser.com / tnbeverything.com - MILESTONE 1

### ISSUE THREAD

**Issue by stweyel** [thenewboston-developers/Projects#219]
### Link to original project proposal.
#167

### Detailed log of all completed objectives including valid proof of work.
| # | Objective             | How can auditors verify milestone?     |
| - | --------------------- | -------------------------------------- |
| 1 | Wireframe of landing page | https://wireframepro.mockflow.com/view/Mb4624c80d8dc597959b422f005ec9c9d1622652695991|
| 2 | Activated domain| https://www.tnbeverything.com/|

### Project Wallet
3a115cb6d87edb299e0ca95393465d171768bb5c2c08c4b27e1cfb4c3141f8ec

#### Github repo:
https://github.com/stweyel/tnbuser.com-tnbeverything.com

**Comment by angle943** [comment]
Approved for 4000.

Please submit your second milestone report once it's ready!
