### ISSUE TITLE
TNBPAY- MILESTONE 1

### ISSUE THREAD

**Issue by olowudaniel1** [thenewboston-developers/Projects#221]
#### Link to the milestone and objectives table.
#172 

#### Detailed log of all completed objectives including valid proof of work.
https://www.figma.com/file/oJz4EO34MvQnBF1q6pvx4b/TnbPAY?node-id=0%3A1

#### Project Wallet
86ee75d4cea77ca8339cc97f5e7426a3434d9f91465cd441c0c7593bd852e955

**Comment by angle943** [comment]
approved for 5,000 coins!

As your next step, please write up a detailed milestone proposal for your next milestone.

**Comment by olowudaniel1** [comment]
Just to be sure, I should draft a milestone proposal for the next milestone before completing it, right? if Yes, should I create it as a new issue

**Comment by manishram** [comment]
Hey @olowudaniel1 yes you are supposed to make a next milestone proposal before working on it.
You can make a new milestone proposal from [HERE](https://github.com/thenewboston-developers/Projects/issues/new?assignees=&labels=Milestone&template=milestone-proposal.md&title=NAME_OF_PROJECT+-+NAME_OF_MILESTONE+-+MILESTONE_NUMBER )
