### ISSUE TITLE
TNB Discord Shop - MVP - 1

### ISSUE THREAD

**Issue by Kycermann** [thenewboston-developers/Projects#227]
#### Link to the milestone and objectives table.
https://github.com/thenewboston-developers/Projects/issues/222

#### Detailed log of all completed objectives including valid proof of work.
Source code: https://github.com/Kycermann/TNB-Shop
Testing server with hosted bot: https://discord.gg/g3MX4JAQU6

#### Project Wallet
f1decb80339a4bb6c089b77cbac553e23a6ca86b0cfc64adb8c8eb8f8b57d815

**Comment by tspearing** [comment]
@Kycermann, we joined the server to test but did not have permission to send any messages. Can you help us out?

**Comment by tspearing** [comment]
@Kycermann, we tried this and sent a transaction to the project wallet but didn't see the role change. Did we miss something?

**Comment by Kycermann** [comment]
> @Kycermann, we tried this and sent a transaction to the project wallet but didn't see the role change. Did we miss something?

The Node version reverted from 14 on my VPS and a part of the bot hanged. I've started it again and posted proof that it works (log channel). It immediately gave out all those roles.

**Comment by Kycermann** [comment]
> @Kycermann, we tried this and sent a transaction to the project wallet but didn't see the role change. Did we miss something?

Hey @tspearing, the Node version reverted from 14 on my VPS and a part of the bot hanged. I've started it again and posted proof (in the test server) that it works (log channel). It immediately gave out all those roles.
