### ISSUE TITLE
aiotnb - Library Core - Milestone 1

### ISSUE THREAD

**Issue by AnonymousDapper** [thenewboston-developers/Projects#228]
### Link to milestone and objective list
[thenewboston-developers/Projects Proposal 215](https://github.com/thenewboston-developers/Projects/issues/215)

### Milestone proof of work

1. HTTP client system
    [Source code](https://github.com/AnonymousDapper/aiotnb/blob/master/aiotnb/http.py#L71)

2. Exceptions library
    [Source code](https://github.com/AnonymousDapper/aiotnb/blob/master/aiotnb/exceptions.py)

3. Type checking
    [Actions workflow overview](https://github.com/AnonymousDapper/aiotnb/actions/workflows/main.yml)

    [Latest Actions run](https://github.com/AnonymousDapper/aiotnb/runs/2766321588?check_suite_focus=true)

    To run a type check on your machine, first install [Pyright](https://github.com/microsoft/pyright), then 

        $ git clone https://github.com/AnonymousDapper/aiotnb.git
        $ cd aiotnb
        $ pyright --pythonversion 3.8 aiotnb

4. JSON validation
    [Source code](https://github.com/AnonymousDapper/aiotnb/tree/master/aiotnb/validation)

5. Testing

    [HTTP test source code](https://github.com/AnonymousDapper/aiotnb/blob/master/tests/test_http.py)

    [JSON Validator test source code](https://github.com/AnonymousDapper/aiotnb/blob/master/tests/test_validation.py)

    [Keypair management test source code](https://github.com/AnonymousDapper/aiotnb/blob/master/tests/test_keypair.py)

    Test results screenshot.

    ![Test results](https://totally-not.a-sketchy.site/7QE7WvH.png)

    `xfail` tests are tests that are meant to fail. This is a good and intended result.

6. Performance Benchmark

    Unfortunately, the network at the current time is not large enough to truly demonstrate the advantage of coroutine functions over normal Python functions. That said, there is still a small speed boost, even with only 2 validator nodes. The average speedup from using aiotnb vs the original library *with two nodes* is **3%**. This will continue to increase as the network gets larger and the library can take advantage of the parallel nature of coroutines.

    [Source code](https://github.com/AnonymousDapper/aiotnb/blob/master/examples/speed_demo.py)

    How to run

    *aiotnb currently requires a minimum python version of 3.8, this will be lowered to 3.6 in a future version*

        $ git clone https://github.com/AnonymousDapper/aiotnb.git
        $ cd aiotnb
        $ git clone https://github.com/thenewboston-developers/thenewboston-python-client.git

        $ pip install virtualenv
        $ virtualenv .venv
        $ . .venv/bin/activate

        $ pip install thenewboston-python-client
        $ pip install .

        $ python examples/speed_demo.py

While working on this milestone my inexperience in estimating work made itself very clear to me, so I'll be submitting a more detailed proposal for milestone 2.

#### Project Wallet
`16c9d5010701093e4427b12d3674024346a6ac90f7cc3cbebc6d3d041d435fdd`

**Comment by tspearing** [comment]
Hi @AnonymousDapper, Manish is going to run some local tests against the code to verify. We'll get back to you shortly.
