### ISSUE TITLE
aiotnb - Bank API - Milestone 2

### ISSUE THREAD

**Issue by AnonymousDapper** [thenewboston-developers/Projects#230]
#### Link to original project proposal
[thenewboston-developers/Projects Proposal 215](https://github.com/thenewboston-developers/Projects/issues/215)

#### Link to previous milestone payout request
[thenewboston-developers/Projects Payout Request 228](https://github.com/thenewboston-developers/Projects/issues/228)

#### ! Addendum to Proposal !
This project proposal was/is my first foray into writing a detailed roadmap of a project, as well as my first experience documenting work for audit. It has come to my attention that my initial proposal did not properly quantify the amount of work required to complete the milestones. I will not ask for a revaluation of milestone 1, as I agreed to the given estimate, but I will be working with an auditor and someone familiar with writing proposals so as to more accurately represent the time and effort involved in writing this library.

## Milestone 2
This milestone revolves around the implemention of the Bank API. The objectives laid out in the original proposal are split out into their own groups and subgroups here to better represent and quantify the technical details.

The end result of this milestone is a complete, 100% functional ready-to-use implementation of the Bank API.

### Endpoint Objectives
These objectives directly correlate to the HTTP requests for the API and the data involved in each. The main verification method here will be reading of the source code or provided documentation.

#### Accounts
1. `GET /accounts` - actual HTTP request to fetch account data
    1. `Account` object to contain the account information (a class instead of just a JSON object)

2. `PATCH /accounts/<account_number>` - HTTP request to set trust for an account
    1. Message signing and signature verification to ensure only trusted nodes can edit account trust

3. Validation schemas to ensure we received the data in a format we understand
    
    This also will convert data types where posssible, ie. a timestamp string will be converted to a timestamp object to make comparison easier

#### Bank Transactions
4. `GET /bank_transactions` - HTTP request to list transactions a bank is aware of
    1. `BankTransaction` object to contain transaction information (a class with attributes for the response data and automatic signature verification)

    2. Testing of signature verification

5. Validation schemas to ensure we received the data in a format we understand
    
    This will also convert data types where possible, ie. a string containing public key data will be converted into a VerifyKey object to make verification and signing easier

#### Banks
6. `GET /banks` - HTTP request to list other banks a primary bank is connected to
    1. `PartialBank` object to contain the bank information *without* making another connection to the bank to retrieve the primary validator data. 

        A separate method will be provided to actually make a connection to the other bank that will be called manually to save bandwidth and memory resources.

7. `PATCH /banks/<node_identifier>` - HTTP request to set trust for a bank
    1. Message signing and signature verification to ensure only trusted nodes can edit bank trust

    2. Find an existing `Bank` or `PartialBank` object with this node identifier and edit its trust value, instead of creating a new object if it exists - saving bandwidth resources, even if only a small amount

8. Validation schemas to ensure we received the data in a format we understand
    
    This will also convert data types where possible, ie. a string containing a URL will be validated to make sure it is a valid URL, then parsed into a [URL](https://yarl.readthedocs.io/en/latest/) object for ease-of-use

#### Blocks
9. `GET /blocks` - HTTP request to retrieve transaction blocks a bank is aware of
    1. `Block` object to contain the block data (with appropriate datatypes and a method for signature verification)

    2. Testing of signature verification

10. `POST /blocks` - HTTP request to add transactions to the blockchain
    1. Message signing and verification to ensure we send a verifiable transaction list

11. Validation schemas for block data - both endpoints return individual block data in the same format

#### Clean
12. `GET /clean` - HTTP request to fetch last clean status
    1. `CleanStatus` object to contain the response data
    
13. `POST /clean` - HTTP request to initiate or stop a cleaning
    1. Message signing and verification to ensure the node responds if we have the correct key

14. Validation schemas for clean data and request data (to ensure a user cannot submit invalid data)

#### Config
15. `GET /config` - HTTP request to fetch a bank's connection information, as well as that of its primary validator
    
    This is the primary endpoint used to connect to a new bank. If the node ID is different, a new `Bank` object is created and returned

    1. `Bank` object to contain config data. 

        This has attributes for the connection information, the transaction information and the bank's primary validator (which is itself a `Validator` object)

16. Validation schemas to ensure the config data is sensible and follows the network standards

#### Confirmation Blocks
17. `GET /confirmation_blocks` - HTTP request to fetch confirmed blockchain data
    1. `ConfirmationBlock` object - if we have a local `Validator` object with the same node ID as the one that validated this block, set that object as an attribute of the `ConfirmationBlock` class, otherwise just use the node ID itself

18. `POST /confirmation_blocks` - HTTP request to send a validated confirmation block to a bank
    1. Account aggregation and final balance calculation

    2. Message signing and verification

19. Validation schemas to ensure properly formatted block data and request data (to ensure a user cannot submit invalid data)

#### Crawl
20. `GET /crawl` - HTTP request to fetch crawl status
    1. `CrawlStatus` object to contain response data

21. `POST /crawl` - HTTP request to initiate or stop a node crawl
    1. Message signing and verification to ensure the node responds if we have a correct key

22. Validation schemas for crawl data

#### Invalid Blocks
23. `GET /invalid_blocks` - HTTP request to fetch invalid block data
    1. `InvalidBlock` object for response data - substitute validator objects for validator node ID if we have a `ConfirmationValidator` or `Validator` object with the same ID

24. `POST /invalid_blocks` - HTTP request to submit an invalid block
    1. Message signing and signature verification

25. Validation schemas for response and request data (to ensure a user cannot submit invalid data)

#### Connection Requests
26. `POST /connection_requests` - HTTP request to initiate a new node connection
    1. Message signing and signature verification

Validation schema here is just an empty object, so it is not itemized.

#### Confirmation Services
27. `GET /validator_confirmation_services` - HTTP request to list confirmation services for a bank
    1. `ConfirmationContract` object to contain response data - substituting validator object if we have one with the same node ID

28. `POST /validator_confirmation_services` - HTTP request to indicate acceptance of validator confirmation service request
    1. Message signing and signature verification

29. Validation schemas for service data

#### Upgrade Notice
30. `POST /upgrade_notice` - HTTP request to inform a bank of a validator upgrade
    1. Message signing and signature verification

    2. Special handling for the HTTP 400 response code sent if the bank remains on its existing network

 #### Validators
31. `GET /validators` - HTTP request to list a bank's connected validators
    1. `PartialValidator` object to contain the validator information *without* making another connection to the validator to retrieve the primary validator data. 

        A separate method will be provided to actually make a connection to the other validator that will be called manually to save bandwidth and memory resources.

32. `GET /validators/<node_identifier>` - HTTP request to list a specific node

33. `PATCH /validators/<node_identifier>` - HTTP request to set trust for a validator
    1. Message signing and signature verification

34. Validation schemas for response data

### Secondary Objectives
These objectives are not the core logic for connecting to the API, but they fulfill the other requirements laid out in the original proposal.

#### Documentation
These objectives involved developer documentation for the library. Verification can be done by reading the source code (for docstrings) and by building and reading the generated html pages (for Sphinx docs).

35. Docstrings (in-source documentation) written for Bank object
    1. Docstrings written for helper objects (Block, Transaction, CrawlStatus, etc)

36. Sphinx docs (HTML "official" documentation) written for Bank object
    1. Sphinx docs writen for helper objects (see above)

#### Testing
Test objectives can be verified by running tests manually, but test results will also be posted.

37. Should-pass tests for endpoints to ensure correct data is processed correctly

38. Should-fail tests for endpoints to ensure invalid data is rejected

39. Should-pass tests for validation schemas to ensure well-formatted data is accepted

40. Should-fail tests for validation schemas to ensure incorrect data is rejected.

#### Other
Type check verification can be achieved by running pyright or viewing the Actions workflow for the final commit of this milestone.

41. Full type-checking for public objects in Bank API. This includes the Bank class itself, any helper classes (Transaction, Block, etc), and all of their methods and attributes.

I am in the process of hiring a graphic artist to design a branding logo for this project and the estimated cost is unknown at this time. I will mention this again in a later milestone.

#### How long do you estimate this milestone will take to complete?
4-6 weeks

#### Project Wallet
`16c9d5010701093e4427b12d3674024346a6ac90f7cc3cbebc6d3d041d435fdd`

**Comment by buckyroberts** [comment]
@AnonymousDapper Approved for 80,000!

**Comment by AnonymousDapper** [comment]
Glad to hear it! I won't disappoint.
