### ISSUE TITLE
TNB Discord Shop - Big Boy Update: Improve, Scale, Polish - 2

### ISSUE THREAD

**Issue by Kycermann** [thenewboston-developers/Projects#234]
#### Link to the milestone and objectives table.
https://github.com/thenewboston-developers/Projects/issues/232

#### Detailed log of all completed objectives including valid proof of work.
Join the test server, the work speaks for itself :)
Invite: https://discord.gg/g3MX4JAQU6

_Changes:_
- Objective 4: Introductory message is too intrusive. Instead the bot sends a message when it's pinged and /commands explain how to set it up if the permissions are wrong.
- Objective 6: It's /admin wallet which is fancier- not only can you set the wallet but also check the address.
- Objective 14: I did set a status but not to the invite link, that's given when pinged and in /shop.
- Objective 22: This is too intrusive. Instead the bot pauses and complains (helpfully!) in all slash commands instead of working- until the errors are fixed.
- Objective 25: Don't 
- Objective 29: This is /admin purchases [optional user filter] [optional role filter]
- Objective 30: This is now /admin purchases without any filters. As a bonus objective, you can filter by roles and/or users or view all purchases :))
- Objective 33: Since server owners manage their own wallets (they weren't going to for a while), they can sort this out by refunding users or just giving them the roles.

#### Project Wallet
f1decb80339a4bb6c089b77cbac553e23a6ca86b0cfc64adb8c8eb8f8b57d815

**Comment by Kycermann** [comment]
PS: To help test, Bucky and Manish, you guys have the TNB Shop Manager and you're welcome to add / remove / modify any of the test roles. Tristan, you don't have the role so the `/admin` commands should be greyed out for you.

**Comment by Kycermann** [comment]
**Bonus update:**
- `/help` command with buttons: FAQ, Security, Scan for new purchases, Support server, Invite bot
- Purchases take 15 seconds to scan instead of 3 minutes due to a nice optimisation I did
- _Manage Channels_ permission isn't required anymore

**Comment by tspearing** [comment]
@Kycermann, please provide screenshots for the objectives which require them.

Also, please see: https://discord.com/channels/851232286133321730/851232286133321733/853104097111310347

**Comment by Kycermann** [comment]
> @Kycermann, please provide screenshots for the objectives which require them.
> 
> Also, please see: https://discord.com/channels/851232286133321730/851232286133321733/853104097111310347

Hey @tspearing, thanks for looking at my milestone:

**VPS**

VPS wise, I won't pre-buy anything because I might need to resize it- but I'm happy to show my 5 year old or so DigitalOcean account billing history- in private!

**Auto restart**

<img width="349" alt="image" src="https://user-images.githubusercontent.com/59399685/121768780-e9cc3680-cb57-11eb-8077-a0d0dac0e2f5.png">


**No transaction re-counting**

The bot fetches up to 100 transactions, compares the `"count"` to the count in the database- and it counts the difference.

<img width="845" alt="image" src="https://user-images.githubusercontent.com/59399685/121768565-b6d57300-cb56-11eb-804f-b37fd4846fe5.png">

<img width="628" alt="image" src="https://user-images.githubusercontent.com/59399685/121768555-a6bd9380-cb56-11eb-8317-3de94054f0ac.png">

**Race condition**

<img width="650" alt="image" src="https://user-images.githubusercontent.com/59399685/121768711-775b5680-cb57-11eb-9857-7f67be17a230.png">

This was fixable for the brief period I was going to accept TNB into a bot wallet- but since it goes into server owners wallets and the race condition rarely happens (not that I could patch it anyway), the server admin can refund- and people are asked to speak to them if they don't receive their role.

**Logo**

See the test Discord.

**Comment by tspearing** [comment]
@Kycermann, on tnbCrow, I bought the role "Tuna-n-Bacon" and then left the server and rejoined and lost the role (objective 9).

Bucky can't see "/shop_admin lookup @user" (objective 24).

In "/shop_admin info" the result might be: 3. @pretty Orange Test | 1 TNBC | 1 sold | 1 day <- what does "1 day" mean?

Can you send an invite link for the bot? We created a new server to test out some of the objectives.

**Comment by tspearing** [comment]
https://discord.com/oauth2/authorize?client_id=850788778704764948&scope=bot+applications.commands&permissions=268435472
