### ISSUE TITLE
.tnbc DNS/Registrar

### ISSUE THREAD

**Issue by denistsoi** [thenewboston-developers/Projects#235]
# Project Details

#### How would you describe your project?
Allow users to purchase domain-like registars as wallet aliases

#### What problem does this project solve?
Have you ever tried to say a wallet address out loud? 

#### Who is the target market?
tnbc holders (who may wish to own a .tnbc address)

#### How will this project benefit the network and/or the community?
Brings convenience to a primary wallet address (i.e. alias)

#### How is this project centered around thenewboston?
owning a `.tnbc` domain

#### What is the estimated completion date for this project? (rough estimates are acceptable)
2 months

#### Please include a detailed roadmap for your project below. This must include a list of all milestones where payments will be awarded upon completion of each.

Milestone | description
--- | --- 
1 | Get up and get running
2 | Protect domains (not for sale/listed for brands) + register via email
3 | Edit domain (edit primary) + Sell/Transfer ownership (buying and selling .tnbc domains)

#### What is your Discord username?
wakawaka#9513

#### Additional files and documentation including architectural diagrams, wireframes, research documents, visuals, etc… (optional)

![tnbc-domain](https://user-images.githubusercontent.com/3061779/121702300-56b5e100-cb04-11eb-8504-ddc8124f138c.png)

# Milestone Details

---

#### First Milestone Description
Getting first features out the door 

#### First Milestone Objectives

| # | Objective             | How can auditors verify milestone?     |
| - | --------------------- | -------------------------------------- |
| 1 | Create BE service     | Project repo and basic templating |
| 2 | REST Create User (discord SSO) | 👆🏻 |
| 3 | REST Create .tnbc domain | 👆🏻 |
| 4 | REST Search domains (availble to purchase) | 👆🏻 |
| 5 | List domains (registered) | 👆🏻 |
| 6 | Backup Transactions (for post-beta)
| 7 | Host website to purchase .tnbc domain  | repo + domain |
| 8 | Provide API docs for keysign + account manager to access api / how to parse memo | markdown |

#### How long do you estimate this first milestone will take to complete?
2 - 4 weeks

#### Project Wallet
edbec48fd474e9f7a6b664bcdd72f91f7c191dffcc6f97f2b7548742ef3b71ed

**Comment by denistsoi** [comment]
https://github.com/commandokoala/tnbc-dns adding new repo here before i start work

**Comment by Kycermann** [comment]
Is this something we could integrate into the core chain along with usernames?

**Comment by denistsoi** [comment]
just read the beta roadmap, seems usernames is already accounted for in roadmap. 🤦🏻‍♂️

**Comment by tspearing** [comment]
@denistsoi, we assume you're going to withdraw this as there will be usernames? Also, it looks like it would require a blockchain architecture change which is against the rules.
