### ISSUE TITLE
TNB Donation - Project Initialization - 1

### ISSUE THREAD

**Issue by Toledit** [thenewboston-developers/Projects#242]
#### Link to the milestone and objectives table.
https://github.com/thenewboston-developers/Projects/issues/193#issue-859777666

#### Detailed log of all completed objectives including valid proof of work.
Approved by gov't: https://github.com/thenewboston-developers/Projects/issues/193#issuecomment-851761789

- Objective 1 
    https://github.com/suppCoins
    https://twitter.com/suppCoins
    https://github.com/suppCoins/Design/issues/1#issue-923189466
- Objective 2
    https://drive.google.com/file/d/1MXc-YmKx5nMLGXC2bFYeNCAdlY7x6ghM/view?usp=sharing
    https://drive.google.com/file/d/1Z7DOerNZv8I4NLAf21ACfNY_L-0LpHt4/view?usp=sharing
-  Objective 3 **(Excluded from payment)**
    https://docs.google.com/spreadsheets/d/1njWtDjnw9T8R8tWTfh5gOWvfcnspolTu4e5I1J-_M-Q/edit?usp=sharing

#### Project Wallet
449baf4c0b43f44e9b091947bf36880bf237a91e413adb85ca2ae1f33e239440

**Comment by tspearing** [comment]
Hi @Toledit, could we get access to the second link in Objective 2?

**Comment by Toledit** [comment]
Oh sorry, here you go:
https://drive.google.com/file/d/1Z7DOerNZv8I4NLAf21ACfNY_L-0LpHt4/view?usp=sharing

**Comment by tspearing** [comment]
Hey @Toledit, we were expecting some more detail on the architecture beyond what was in the proposal. Could we get some new docs outlining the architecture on a deeper level?

The logo looks really good.

**Comment by Toledit** [comment]
@tspearing here's the revised architecture: https://www.figma.com/file/uPiBgmqLBs9Nzrcs38uJBm/SuppCoins-Architecture?node-id=3%3A2
