### ISSUE TITLE
TNBList - Init - 1

### ISSUE THREAD

**Issue by avinashupadhya99** [thenewboston-developers/Projects#243]
#### Link to the milestone and objectives table.
#170 

#### Detailed log of all completed objectives including valid proof of work.

| # | Objective           | Proof of work  |
| - | ------------------- | ------------------------- |
| 1 | Create UI wireframes | https://wireframepro.mockflow.com/view/M1331666c68f083aa51e5457889ae749c1621927521757 (Check UI wireframe page) |
| 2 | Create Sitemap | https://wireframepro.mockflow.com/view/M1331666c68f083aa51e5457889ae749c1621927521757 (Check Sitemap page) |
| 3 | Setup repos along with CICD | https://github.com/TNB-List/Website, https://github.com/TNB-List/User-Service (CICD is also implemented, please check the Actions tab) |
| 4 | Setup VM on cloud or setup a PaaS for deployment | https://tnb-list.uc.r.appspot.com/, https://user-dot-tnb-list.uc.r.appspot.com/ |
| 5 | Setup static code analysis | http://34.68.121.232/, https://github.com/TNB-List/User-Service/actions/runs/945727672, https://github.com/TNB-List/Website/actions/runs/945757407 |

#### Project Wallet

`94cf53921e9c5ddf48dc5589b7cdf111f7acdc93dc3073b94880416d4676b9ae`

**Comment by tspearing** [comment]
Hi @avinashupadhya99, looks good.

In the design, could you remove the section in the payment page where it asks for the signing key? Keysign will be great and TNBPay is another option (https://github.com/thenewboston-developers/Projects/issues/172).

Beyond that, this is approved and you can proceed to submitting milestone #2.
