### ISSUE TITLE
tnbc Paper Wallet

### ISSUE THREAD

**Issue by hussu010** [thenewboston-developers/Projects#244]
# Project Details

#### How would you describe your project?
A website that lets you generate paper wallets for TNBC. The users can generate and print cool paper wallets with QR code attached. 

#### What problem does this project solve?
Lets users create paper wallets for TNBC.

#### Who is the target market?
Users who like to store keys on paper rather than somewhere on the internet.

#### How will this project benefit the network and/or the community?
Lets people generate printable nice-looking paper wallets.

#### How is this project centered around thenewboston?
Its specifically made for tnbc

#### What is the estimated completion date for this project? (rough estimates are acceptable)
One month

#### Please include a detailed roadmap for your project below. This must include a list of all milestones where payments will be awarded upon completion of each.
- UX/ UI of the application + Paper wallets designs (8 included)
- Front-end development

#### What is your Discord username?
hussu#9966

#### Additional files and documentation including architectural diagrams, wireframes, research documents, visuals, etc… (optional)
Wireframes:
![download](https://user-images.githubusercontent.com/55182298/122444406-3a142000-cfc0-11eb-8229-ea13ed96433b.png)

# Milestone Details

Please include a detailed breakdown of the first milestone including a list of all quantifiable objectives. Upon 
completion of the milestone, each objective will be reviewed by thenewboston team and once all objectives have been 
verified as completed, coins will then be rewarded.

Note that all future detailed milestone breakdowns will be written as a separate GitHub issue. Only the first milestone 
is included in this project proposal.

---

#### First Milestone Description
The first milestone will be to create the UX/ UI of the application. The designs of the paper wallets to be printed are also included. We'll be making 8 different variants of paper wallets which consist of the account number, signing key, and QR code for both.

#### First Milestone Objectives

| # | Objective             | How can auditors verify milestones?     |
| - | --------------------- | -------------------------------------- |
| 1 | UX/ UI of website | Figma files |
| 2 | Paper wallets designs | PNG files |

#### How long do you estimate this first milestone will take to complete?
14 days

#### Project Wallet
79c0d308e31b9c4cf0f2bdaae65e2d8476c355084035ee11755facaa9597ff98

**Comment by tspearing** [comment]
Hey @hussu010, we really like this idea and want to fund it.

Regarding the first milestone, as a general rule, we require the design as part of the proposal (though there's some above). Consequently, if we make more advanced figma drawings a part of the milestone, we propose a payout of 5000 TNBC for the first milestone.

After the first milestone, could we propose:
1) Use the users mouse to randomly generate the signing key. See this for an example: https://paperwallet.bitcoin.com/cashwallet.html
Note they have a github link: https://github.com/Bitcoin-com/paperwallet.bitcoin.com/

2) Make sure it works when the user is offline. So they could turn their internet connection off and generate their keys or download the code locally.
