### ISSUE TITLE
Hd Wallets for TNB - Key Generation Website - Milestone 2

### ISSUE THREAD

**Issue by tomijaga** [thenewboston-developers/Projects#250]
#### Link to the original project proposal.
https://github.com/thenewboston-developers/Projects/issues/198

#### Link to most recent milestone payout request.
https://github.com/thenewboston-developers/Projects/issues/248

#### Milestone Description
A simple react website for generating public and private keys from a 12-word mnemonic phrase using the [tnb-hd-wallet typescript package](https://www.npmjs.com/package/tnb-hd-wallet). 

| # | Objective             | How can auditors verify milestone?     |
| - | --------------------- | -------------------------------------- |
| 1 | Input for 12 Word Mnemonic Phrase | Website & Source code |
| 2 | Validation of Mnemonic Phrase | Website & Source code |
| 3 | Key derivations for all the cryptocurrencies implemented in the package  | Website & Source code |
| 4 | Display a table with the derived addresses path, public keys and private keys | Website & Source code |
| 5 | Ability to hide derived addresses | Website & Source code |

#### How long do you estimate this milestone will take to complete?
Its already complete 

#### Project Wallet
8de30226230c35bbc1ce4a63c62a7b9c86bf0ce21fc7bc1a984b7884a9f88782

**Comment by tspearing** [comment]
@tomijaga, we approve this milestone and propose 10 000 TNBC.

**Comment by tomijaga** [comment]
Great! I've submitted the payment request at this link  https://github.com/thenewboston-developers/Projects/issues/251
