### ISSUE TITLE
Hd Wallet for TNB - Key Generation Website - Milestone 2

### ISSUE THREAD

**Issue by tomijaga** [thenewboston-developers/Projects#251]
#### Link to the milestone and objectives table.
https://github.com/thenewboston-developers/Projects/issues/250

### Detailed log of all completed objectives including valid proof of work.
[Source Code](https://github.com/tomijaga/hd-keygen)
[Website](https://hd-keygen.vercel.app/)

### Comparison with an existing keygen website
Mnemonic Phrase:
 **protect oppose review emotion damp trash bleak notice hawk sentence follow achieve**
 
> Note: The phrase above should not be used to store coins as the keys are exposed in the sreenshots below
 #### Bitcoin
https://iancoleman.io/bip39/
![image](https://user-images.githubusercontent.com/50385769/122646959-ca19ad00-d119-11eb-89e0-52f99a850476.png)

https://hd-keygen.vercel.app/
![image](https://user-images.githubusercontent.com/50385769/122646766-d5200d80-d118-11eb-85b6-15c0f1ed50aa.png)

#### Ethereum
https://iancoleman.io/bip39/
![image](https://user-images.githubusercontent.com/50385769/122646919-8fb01000-d119-11eb-9419-97dc3b26a223.png)

https://hd-keygen.vercel.app/
![image](https://user-images.githubusercontent.com/50385769/122646929-9cccff00-d119-11eb-8beb-c1f2d05293ff.png)

#### Project Wallet
8de30226230c35bbc1ce4a63c62a7b9c86bf0ce21fc7bc1a984b7884a9f88782

**Comment by tspearing** [comment]
Approved for 10 000 TNBC.
