### ISSUE TITLE
TNBC Analytics (open source auditing/analytics tools)

### ISSUE THREAD

**Issue by SazidAhmed** [thenewboston-developers/Projects#255]
# Project Details

#### How would you describe your project?
TNBC Analytics is a web app to track TNBC transactions from treasury to government and government to other distributed TNBC accounts for transparency and accountability. 

#### What problem does this project solve?
It would help the community to keep tracking on the transactions made by the government.

#### Who is the target market?
All the people who want to audit the transactions of government.

#### How will this project benefit the network and/or the community?
It would help the core team and government build trust among community members and provide transparency.

#### How is this project centered around thenewboston?
This service is particularly for TNBC.

#### What is the estimated completion date for this project? (rough estimates are acceptable)
Our estimated time to complete the MVP is within next two months. It could be declared as August 2021

#### Please include a detailed roadmap for your project below. This must include a list of all milestones where payments will be awarded upon completion of each.

Software Architecture and Complete UX/ UI Design 
Frontend and Backend development
Testing and Deployment

#### What is your Discord username?
SazidAhmed#8192

#### Additional files and documentation including architectural diagrams, wireframes, research documents, visuals, etc… (optional)

- wireframe : https://www.figma.com/file/vF1qxpJLAyzbRFABAtK92m/TNBC-Analytics?node-id=0%3A1

# Milestone Details

Please include a detailed breakdown of the first milestone including a list of all quantifiable objectives. Upon 
completion of the milestone, each objective will be reviewed by thenewboston team and once all objectives have been 
verified as completed, coins will then be rewarded.

Note that all future detailed milestone breakdowns will be written as a separate GitHub issue. Only the first milestone 
is included in this project proposal.

---

#### First Milestone Description
In this milestone we’re going to work on Software Architecture and a complete working version of UX/ UI design.

#### First Milestone Objectives

| # | Objective             | How can auditors verify milestone?     |
| - | --------------------- | -------------------------------------- |
| 1 | Software Architecture |  Architectural documents, ERD, UML diagram and database design would be provided |
| 2 | UX/ UI design | Figma project of the UI/UX design would be provided |

#### How long do you estimate this first milestone will take to complete?
2 weeks

#### Project Wallet
a5dbcded3501291743e0cb4c6a186afa2c87a54f4a876c620dbd68385cba80d0

**Comment by tspearing** [comment]
Hi @SazidAhmed, we approve this project and propose a payout of 25000 TNBC for the first milestone.

**Comment by SazidAhmed** [comment]
@tspearing Thanks to Audit team and the Government for approving the project.

**Comment by SazidAhmed** [comment]
Here is the github repository of the project : https://github.com/Techminate/TNBC-Analytics

**Comment by SazidAhmed** [comment]
@tspearing hello, would you please tell me how to submit the first milestone report.
Is there any format of report that I should follow ?

**Comment by manishram** [comment]
Hey @SazidAhmed  you can make a milestone payout request from [HERE](https://github.com/thenewboston-developers/Projects/issues/new?assignees=&labels=Milestone+Payout+Request&template=milestone-payout-request.md&title=NAME_OF_PROJECT+-+NAME_OF_MILESTONE+-+MILESTONE_NUMBER).
