### ISSUE TITLE
TNB-DISCORD BOT - whole bot - 1

### ISSUE THREAD

**Issue by mrbusysky** [thenewboston-developers/Projects#257]
#### Link to the milestone and objectives table.
https://github.com/thenewboston-developers/Projects/issues/256

#### Detailed log of all completed objectives including valid proof of work.
The bot is working all features can be tested live
https://docs.google.com/document/d/1NYFMZuqcubAGCYPB7bBYUC6rCjyqRP9kh5XOp6IJ6q0/edit

#### Project Wallet
32d8b9aeb1646c9e17d90b36451ce5b853b6e72cbeaf65ad8d7687137b683ee6

**Comment by tspearing** [comment]
Approved for 40800 TNBC.
