### ISSUE TITLE
NAME_OF_YOUR_PROJECT

### ISSUE THREAD

**Issue by radhmatt** [thenewboston-developers/Projects#258]
write a pseudocode for a program that sets a variable named username as "MyUserName" and another variable named password as "MyPassword" then asks the user to enter the username and password. If the correct username and password are entered the program should display "Logged in" otherwise the program should display either "Incorrect Password" or "Incorrect Username" as appropriate. It should also allow the user to make another attempt at entering the combination. The user should be allowed a maximum of THREE attempts to get the correct password. 

#### How would you describe your project?
RADHMATT WIFI

#### What problem does this project solve?
security 

#### Who is the target market?
ANSWER HERE

#### How will this project benefit the network and/or the community?
ANSWER HERE

#### How is this project centered around thenewboston?
ANSWER HERE

#### What is the estimated completion date for this project? (rough estimates are acceptable)
ANSWER HERE

#### Please include a detailed roadmap for your project below. This must include a list of all milestones where payments will be awarded upon completion of each.
ANSWER HERE

#### What is your Discord username?
DISCORD USERNAME HERE (https://discord.gg/thenewboston)

#### Additional files and documentation including architectural diagrams, wireframes, research documents, visuals, etc… (optional)
- OPTIONAL ATTACHMENT HERE
- OPTIONAL ATTACHMENT HERE
- OPTIONAL ATTACHMENT HERE

# Milestone Details

Please include a detailed breakdown of the first milestone including a list of all quantifiable objectives. Upon 
completion of the milestone, each objective will be reviewed by thenewboston team and once all objectives have been 
verified as completed, coins will then be rewarded.

Note that all future detailed milestone breakdowns will be written as a separate GitHub issue. Only the first milestone 
is included in this project proposal.

---

#### First Milestone Description
SHORT DESCRIPTION OF MILESTONE HERE

#### First Milestone Objectives

| # | Objective             | How can auditors verify milestone?     |
| - | --------------------- | -------------------------------------- |
| 1 | OBJECTIVE DESCRIPTION | EXPLANATION OF HOW AUDITORS CAN VERIFY |
| 2 | OBJECTIVE DESCRIPTION | EXPLANATION OF HOW AUDITORS CAN VERIFY |
| 3 | OBJECTIVE DESCRIPTION | EXPLANATION OF HOW AUDITORS CAN VERIFY |

#### How long do you estimate this first milestone will take to complete?
ANSWER HERE

#### Project Wallet
PROJECT WALLET ACCOUNT NUMBER HERE

**Comment by hussu010** [comment]
![download (4)](https://user-images.githubusercontent.com/55182298/123931821-9871d300-d9b0-11eb-881e-a075a45173fc.png)

**Comment by manishram** [comment]
@radhmatt 
**TNB Projects** welcome people to come up with ideas that have the potential to add value to thenewboston and TNB will help with funds to build them up.

Learn more about projects by clicking [here](https://thenewboston.com/project-rules/overview#how-proposals-work)
