### ISSUE TITLE
Gamer Arena - Milestone 1 for the BLOG

### ISSUE THREAD

**Issue by olowudaniel1** [thenewboston-developers/Projects#264]
#### Link to the milestone and objectives table.
#249 

UI/UX Design of web pages for the Blog
https://www.figma.com/file/dutfNRhzRTKzQ1zcxYsOPr/tournament?node-id=0%3A1

Account Number
86ee75d4cea77ca8339cc97f5e7426a3434d9f91465cd441c0c7593bd852e955

**Comment by tspearing** [comment]
Hi @olowudaniel1, we propose 5000TNBC for this milestone.

**Comment by olowudaniel1** [comment]
Okay
