### ISSUE TITLE
TNBC Analytics  - Software Architecture and Complete UX/ UI Design - MILESTONE 01

### ISSUE THREAD

**Issue by SazidAhmed** [thenewboston-developers/Projects#265]
#### Link to the milestone and objectives table.
https://github.com/thenewboston-developers/Projects/issues/255

#### Detailed log of all completed objectives including valid proof of work.
Objective 1 : Software Architecture
Architectural Document : https://drive.google.com/file/d/1c37JACKCF4AORYSMUGrK0ZRdPXFEATtZ/view?usp=sharing 
ERD :  https://drive.google.com/file/d/14HPgb8qW5n6zQitLRaWkDuikcX9tZyc-/view?usp=sharing
Database Design : https://drive.google.com/file/d/1mRUUhH755HjcnaE9bY992LSmNR91GTIj/view?usp=sharing
UML : https://drive.google.com/file/d/1MtgXngOtMxGCDyccR1mQx4-RcLfrSm3n/view?usp=sharing

Objective 2 : UI/UX Design
Figma project link : https://www.figma.com/file/BFs7rxvYFixhH78ipqIzVV/Home-page?node-id=0%3A1
Prototype Link : https://www.figma.com/proto/BFs7rxvYFixhH78ipqIzVV/Home-page?node-id=6%3A2&scaling=scale-down&page-id=0%3A1&starting-point-node-id=6%3A2

#### Project Wallet
a5dbcded3501291743e0cb4c6a186afa2c87a54f4a876c620dbd68385cba80d0

**Comment by tspearing** [comment]
Hi @SazidAhmed, one question:
We don't understand the need for users who are able to login. What does this accomplish? We expected this to be similar to TNBExplorer where users just go to the page and use it with not login necessary.
![image](https://user-images.githubusercontent.com/77364430/126251560-30b44377-36bb-497c-8588-f6f009334344.png)
2)

**Comment by SazidAhmed** [comment]
@tspearing hi, hope you are fine. 
Sorry for making you confused. By the "User" object I wanted to mean admin/manager who would manage the website. 
The website would be open for all the users  similar to TNBExplorer and there are no register and login credentials for general users. 
I thought, Instead of hard code, the contents of the website would be inserted dynamically and it would faster the development progress and also would be easy to maintain. So I added a simple content management model in the ERD so that team, faq, settings and donate objects can be maintain from a simple admin portal. We would use django admin portal as the content management system. So I didn't add any UI design. The only purpose of the "User" object is make the developers understand that these contents would be dynamic.
Is it fine if I rename "User" object as "Admin".
![ERD_TNBC_Analytics](https://user-images.githubusercontent.com/39996870/126303113-c7538139-1169-4f53-bd95-cd913e2630ea.png)

**Comment by tspearing** [comment]
@SazidAhmed, great - thanks for the update!
