### ISSUE TITLE
TNBPAY - MILESTONE 4

### ISSUE THREAD

**Issue by olowudaniel1** [thenewboston-developers/Projects#267]
#### Link to original project proposal.
#172 

#### Link to most recent milestone payout request.
#263 

#### Milestone Description
HI-fi design and Development of the Shopify payment plugin.

Objectives
1. Design the UI/UX for the shopify plugin
2. Development of the plugin
3. Testing
4. Documentation

#### How long do you estimate this milestone will take to complete?
1 month

#### Project Wallet
86ee75d4cea77ca8339cc97f5e7426a3434d9f91465cd441c0c7593bd852e955

**Comment by tspearing** [comment]
Hi @olowudaniel1,

Will there be any cross over between the woo commerce and the shopify plugins? For example, would the modal which pops up to show the account number and memo be the same?

For objective 1, will a figma document be delivered?

**Comment by tspearing** [comment]
@olowudaniel1, we approve this for 50000 TNBC.

**Comment by olowudaniel1** [comment]
Okay
