### ISSUE TITLE
GAMER ARENA (GAME CENTER) - MILESTONE 1

### ISSUE THREAD

**Issue by olowudaniel1** [thenewboston-developers/Projects#268]
I want to change the name of the project to GAME CENTER

#### Link to original project proposal.
#249 

#### Link to most recent milestone payout request.
#264 

#### Milestone Description
Complete Wireframe design  for the Web App

Objective
Complete Wireframe design of all pages.  This will also  include a detailed user flow of the web app.

Please this is not a sitemap, I understand that Sitemaps are expected to be submitted on project proposal.  This is a detailed wireframe design/ UI mockup and it is of utmost importance because of the complexity of the app. Hi-fi design cannot be created without having this wireframing.  The wireframe would contain all pages ( estimation of a minimum of 20 pages). Also, we would work extra hours to ensure this is achieved ASAP.

#### How long do you estimate this milestone will take to complete?
2 weeks

#### Project Wallet
86ee75d4cea77ca8339cc97f5e7426a3434d9f91465cd441c0c7593bd852e955

**Comment by tspearing** [comment]
Hi @olowudaniel1, 

1) How will this be different from the previous milestone?

2) What will the 20 pages be?

**Comment by tspearing** [comment]
@olowudaniel1, we approve this milestone for 8000 TNBC. We'd like to see the pages connect. For example, if someone clicks on the 'dashboard' button, it should open the dashboard.

**Comment by olowudaniel1** [comment]
Okay
