### ISSUE TITLE
SuppCoins - Prototype UI/UX - 2

### ISSUE THREAD

**Issue by Toledit** [thenewboston-developers/Projects#269]
#### Link to the milestone and objectives table.
https://github.com/thenewboston-developers/Projects/issues/193#issue-859777666

#### Detailed log of all completed objectives including valid proof of work.
https://www.figma.com/file/NGV97EooP8yiDPSI9GwCOg/SuppCoins?node-id=0%3A1

#### Project Wallet
449baf4c0b43f44e9b091947bf36880bf237a91e413adb85ca2ae1f33e239440

**Comment by tspearing** [comment]
Approved

**Comment by manishram** [comment]
Approved for 20000 TNBC.

**Comment by Toledit** [comment]
I believe the paid amount doesn't match the approved ammount.
