### ISSUE TITLE
aiotnb - Bank API - Milestone 2 (Payout Request)

### ISSUE THREAD

**Issue by AnonymousDapper** [thenewboston-developers/Projects#271]
### Link to milestone and objective list
[thenewboston-developers/Projects Milestone 230](https://github.com/thenewboston-developers/Projects/issues/230)

I believe this is the most intensive milestone, due to the boilerplate that needs to be written. Ideally, the other API milestones can mostly build off this one.

#### Accounts

1. [`GET /accounts`](https://github.com/AnonymousDapper/aiotnb/blob/bank-api/aiotnb/bank.py#L199-L255)

2. [`PATCH /accounts/<account_number>`](https://github.com/AnonymousDapper/aiotnb/blob/bank-api/aiotnb/bank.py#L257-L303)

3. [`Account` class](https://github.com/AnonymousDapper/aiotnb/blob/bank-api/aiotnb/common.py#L46-L107)

#### Bank Transactions
4. [`GET /bank_transactions`](https://github.com/AnonymousDapper/aiotnb/blob/bank-api/aiotnb/bank.py#L305-L386)

5. [`BankTransaction` class](https://github.com/AnonymousDapper/aiotnb/blob/bank-api/aiotnb/common.py#L203-L257)

#### Banks
6. [`GET /banks`](https://github.com/AnonymousDapper/aiotnb/blob/bank-api/aiotnb/bank.py#L388-L443)

7. [`PATCH /banks/<node_identifier>`](https://github.com/AnonymousDapper/aiotnb/blob/bank-api/aiotnb/bank.py#L445-L495)

8. [`Bank` class](https://github.com/AnonymousDapper/aiotnb/blob/bank-api/aiotnb/bank.py#L74)

    - [`BankDetails` class for incomplete data](https://github.com/AnonymousDapper/aiotnb/blob/bank-api/aiotnb/common.py#L110-L200)

#### Blocks
9. [`GET /blocks`](https://github.com/AnonymousDapper/aiotnb/blob/bank-api/aiotnb/bank.py#L497-L551)

10. [`POST /blocks`](https://github.com/AnonymousDapper/aiotnb/blob/bank-api/aiotnb/bank.py#L553-L584)
    
    This method is not public. A more ergonomic user-facing method will be added once the Validator API is operational.

11. [`Block` class](https://github.com/AnonymousDapper/aiotnb/blob/bank-api/aiotnb/common.py#L260-L322)

#### Clean
These methods return a 2-tuple in the form `(Optional[str], Optional[datetime.datetime])` containing the clean status and last run time.

12. [`GET /clean`](https://github.com/AnonymousDapper/aiotnb/blob/bank-api/aiotnb/bank.py#L586-L607)

13. [`POST /clean`](https://github.com/AnonymousDapper/aiotnb/blob/bank-api/aiotnb/bank.py#L609-L657)

#### Config
15. [`GET /config`](https://github.com/AnonymousDapper/aiotnb/blob/bank-api/aiotnb/bank.py#L659-L680)

#### Confirmation Blocks
17. [`GET /confirmation_blocks`](https://github.com/AnonymousDapper/aiotnb/blob/bank-api/aiotnb/bank.py#L682-L731)

18. `POST /confirmation_blocks`
    - This endpoint has been delayed until milestone 3, as it is deeply connected with the Validator API and I do not yet know how the two need to interact in aiotnb.

19. [`ConfirmationBlock` class](https://github.com/AnonymousDapper/aiotnb/blob/bank-api/aiotnb/common.py#L325-L380)

#### Crawl
These methods return a 2-tuple in the form `(Optional[str], Optional[datetime.datetime])` containing the crawl status and last run time.

20. [`GET /crawl`](https://github.com/AnonymousDapper/aiotnb/blob/bank-api/aiotnb/bank.py#L735-L756)

21. [`POST /crawl`](https://github.com/AnonymousDapper/aiotnb/blob/bank-api/aiotnb/bank.py#L758-L806)

#### Invalid Blocks
23. [`GET /invalid_blocks`](https://github.com/AnonymousDapper/aiotnb/blob/bank-api/aiotnb/bank.py#L808-L855)

24. `POST /invalid_blocks`
    - This endpoint has been delayed until milestone 3, as it is deeply connected with the Validator API and I do not yet know how the two need to interact in aiotnb.

25. [`InvalidBlock` class](https://github.com/AnonymousDapper/aiotnb/blob/bank-api/aiotnb/common.py#L431-L493)

#### Connection Requests
26. [`POST /connection_requests`](https://github.com/AnonymousDapper/aiotnb/blob/bank-api/aiotnb/bank.py#L859-L947)

#### Confirmation Services
27. [`GET /validator_confirmation_services`](https://github.com/AnonymousDapper/aiotnb/blob/bank-api/aiotnb/bank.py#L949-L1005)

28. [`POST /validator_confirmation_services`](https://github.com/AnonymousDapper/aiotnb/blob/bank-api/aiotnb/bank.py#L1007-L1060)

29. [`ConfirmationService` class](https://github.com/AnonymousDapper/aiotnb/blob/bank-api/aiotnb/common.py#L383-L428)

#### Upgrade Notice
30. [`POST /upgrade_notice`](https://github.com/AnonymousDapper/aiotnb/blob/bank-api/aiotnb/bank.py#L1062-L1113)

#### Validators
31. [`GET /validators`](https://github.com/AnonymousDapper/aiotnb/blob/bank-api/aiotnb/bank.py#L1115-L1170)

32. [`GET /validators/<node_identifier>`](https://github.com/AnonymousDapper/aiotnb/blob/bank-api/aiotnb/bank.py#L1172-L1201)

33. [`PATCH /validators/<node_identifier>`](https://github.com/AnonymousDapper/aiotnb/blob/bank-api/aiotnb/bank.py#L1203-L1251)

34. `Validator` class (*TODO in milestone 3*)
    - [`ValidatorDetails` class for incomplete data](https://github.com/AnonymousDapper/aiotnb/blob/bank-api/aiotnb/common.py#L496-L610)

#### Documentation
35. Docstrings can be viewed directly in the source code. (They are the triple-quoted strings)

36. Sphinx documentation can be viewed in the [`docs`](https://github.com/AnonymousDapper/aiotnb/blob/bank-api/docs) directory, and can be built locally using the sphinx tools.

#### Testing

The Bank API tests can be found [here](https://github.com/AnonymousDapper/aiotnb/blob/bank-api/tests/test_bank.py).

Below are the most recent test results from my machine.

![Test results](https://totally-not.a-sketchy.site/4ZYRzNE.png)

#### Performance Benchmark

With more endpoints added, I was able to more completely demonstrate the advantages of coroutine functions. Below are two benchmark results, each requesting a paginated endpoint with 10 results per page. 

- GET /accounts

        [tnb]    Gathered 59 accounts (10-per-page) in 1105.2920ms
        [aiotnb] Gathered 59 accounts (10-per-page) in 763.9069ms
        [aiotnb] Faster by 45%

- GET /bank_transactions

        [tnb]    Gathered 2480 transactions (10-per-page) in 46557.3603ms
        [aiotnb] Gathered 2480 transactions (10-per-page) in 26076.7197ms
        [aiotnb] Faster by 79%

Feel free to edit the benchmark to use different parameters or different endpoints and run it for yourself.

[Source code](https://github.com/AnonymousDapper/aiotnb/blob/master/examples/speed_demo.py)

How to run

    $ git clone https://github.com/AnonymousDapper/aiotnb.git
    $ cd aiotnb
    $ git clone https://github.com/thenewboston-developers/thenewboston-python-client.git

    $ pip install virtualenv
    $ virtualenv .demo
    $ . .demo/bin/activate

    $ pip install thenewboston-python-client
    $ pip install .

    $ python examples/speed_demo.py

#### Project Logo

I commissioned a logo and banner for this project, as requested by the Projects team. The artist was [@denistsoi](https://github.com/denistsoi) (wakawaka#9513 on Discord).

I am requesting an additional remittance of **12 hours worth of work** at the core team's rate, as per his invoice.

See the issue [here](https://github.com/AnonymousDapper/aiotnb/issues/15)

### Final Note
Due to some schedule changes, this has taken me much longer than I anticipated, as I do not have as much free time as before. I expect to get the next milestone proposal submitted the weekend of the 8th, but due to some family circumstances I cannot promise that.

#### Project Wallet
`16c9d5010701093e4427b12d3674024346a6ac90f7cc3cbebc6d3d041d435fdd`

**Comment by manishram** [comment]
Hey @AnonymousDapper we approved this milestone. But regarding the logo, the marketing team is going to pay it separately.
