### ISSUE TITLE
TNBC Games - MILESTONE 1- 

### ISSUE THREAD

**Issue by olowudaniel1** [thenewboston-developers/Projects#275]
#### Link to the milestone and objectives table.
#268 

#### Detailed log of all completed objectives including valid proof of work.
https://whimsical.com/tnbc-games-439zkbRtHN5xmLUyX353Sw

#### Project Wallet
86ee75d4cea77ca8339cc97f5e7426a3434d9f91465cd441c0c7593bd852e955

**Comment by tspearing** [comment]
Approved.
