### ISSUE TITLE
TNBC POS - Design of Architecture and system core - MILESTONE 01

### ISSUE THREAD

**Issue by SazidAhmed** [thenewboston-developers/Projects#276]
#### Link to the milestone and objectives table.
https://github.com/thenewboston-developers/Projects/issues/254

#### Detailed log of all completed objectives including valid proof of work.

Objective 1 : Analysis software concept	
HIPO Diagram : https://drive.google.com/file/d/11n2nRgUad9PHoeVr5yGDe0ExQjSDfiEV/view?usp=sharing
DFD :  https://drive.google.com/file/d/1obA9rBQ_7quYtMmnSjSoCqSsC47hf_j8/view?usp=sharing   
  
Objective 2 : Functional and technical requirements	
Document : https://drive.google.com/file/d/1VtiiRoEpDGIZVj9NFIkMFH6ZMdU95JNk/view?usp=sharing 

Objective 3 : UI/UX design
Figma Project Link : https://www.figma.com/file/rZI1PuWJxcYKQBYx59Atbl/TNBC-POS?node-id=0%3A1   
                  
Objective 4 : Data modeling
ERD :  https://drive.google.com/file/d/1tTiHW6DfRD2Xhaf7PKbv9p8z78ACm6Oa/view?usp=sharing
UML : https://drive.google.com/file/d/1V4FOIXadJBu3mpo-N8S2HWOYQDo1tq5J/view?usp=sharing

#### Project Wallet
a5dbcded3501291743e0cb4c6a186afa2c87a54f4a876c620dbd68385cba80d0

**Comment by tspearing** [comment]
Approved.
