### ISSUE TITLE
Origami: The TNBC Paper Wallet - UX/ UI - 1

### ISSUE THREAD

**Issue by hussu010** [thenewboston-developers/Projects#277]
#### Link to the milestone and objectives table.
https://github.com/thenewboston-developers/Projects/issues/244

#### Detailed log of all completed objectives including valid proof of work.
**Branding**: Origami is the art of paper folding, which is often associated with Japanese culture. In modern usage, the word "origami" is used as an inclusive term for all folding practices, regardless of their culture of origin. The users will be able to fold the paper wallet, make cool shapes, and gift their loved ones.

**HiFi UX/ UI**: https://www.figma.com/file/jVI9KXfqvCtmETzO9FaXKp/Origami-Paper-Wallet

**Logo Versions**:
https://cdn.discordapp.com/attachments/819968712823013416/881001174445223986/Origami-Dark.png
https://cdn.discordapp.com/attachments/819968712823013416/881001172150915123/Origami-Red.png
https://cdn.discordapp.com/attachments/819968712823013416/881001168992632852/Origami-Red-DarkMode.png
https://cdn.discordapp.com/attachments/819968712823013416/881001001857990716/Origami-Black-Full-Outline-Transparent.png

**Note**: We decided to have only one MVP paper wallet design for now. We will move forward with the development first and come back to design foldable paper wallets.

#### Project Wallet
79c0d308e31b9c4cf0f2bdaae65e2d8476c355084035ee11755facaa9597ff98

**Comment by denistsoi** [comment]
![Paper Wallet 22082021-V1-Origami](https://user-images.githubusercontent.com/3061779/130360652-175f1f4c-d94b-45d0-9767-ffa1f781f5da.png)

**Comment by tspearing** [comment]
@hussu010, please let us know when this milestone payout request is ready for review.

**Comment by hussu010** [comment]
Hi @tspearing the milestone is ready to be reviewed and valued accordingly. Thanks :D

**Comment by tspearing** [comment]
@hussu010, Approved.
