### ISSUE TITLE
tnbuser.com / tnbeverything.com - Layout of content / Complete Sitemap wireframe - 2

### ISSUE THREAD

**Issue by stweyel** [thenewboston-developers/Projects#286]
#### Link to the milestone and objectives table.
#167

#### Detailed log of all completed objectives including valid proof of work.
Sitemap wireframe & content layout including descriptions:
https://www.figma.com/file/HXFGXqSMWwv9tP0hsr6OGc/tnbeverything.com-content?node-id=0%3A1

MVP: Preview & testing site:
www.tnbeverything.com

#### Project Wallet
3a115cb6d87edb299e0ca95393465d171768bb5c2c08c4b27e1cfb4c3141f8ec

**Comment by tspearing** [comment]
@stweyel, the original milestone was approved for 76k TNBC which had 10 objectives. Please submit a milestone payout request once all 10 have been completed.

**Comment by stweyel** [comment]
@tspearing 
sorry i don't understand what you mean? 
The approved project proposal included 10 milestones, so it sounds like i have to completely finish the project before submitting a payment request for a milestone?

**Comment by tspearing** [comment]
@stweyel, yes, on the original proposal milestones and objectives are crossed over, but milestones are supposed to relate to payouts and objectives are goals. 

On the original proposal (https://github.com/thenewboston-developers/Projects/issues/167), Justin wrote "approved, and milestone 1 (all 10 objectives) approved for 76,000! (https://github.com/thenewboston-developers/Projects/issues/167#issuecomment-851775898)".

The original payout for milestone 1 for 4000 TNBC was an exception because it included the purchase of the domain.

**Comment by stweyel** [comment]
@tspearing 
ok so if i understand it right the reason for the payout reject is that what initially was proposed as a project including 10 milestones was approved as a project with 1 milestone including 10 objectives?
To be honest i missed that phrasing in Justins comment. However this was never introduced by me and doesn't make sense at all. I guess this was written by mistake by Justin? Maybe @angle943 can comment on this?
The project is a website. So was written the proposal and the milestones have been layed out clearly.  Considering the final release including all content and all works as the one and only milestone of this project would contradict all common means of a milestone in context of a website. It also would be contrary to Buckys statement on discord: "To clarify, this does not mean that the entire project has to be completed at once in order to receive a milestone payout. Only that the project has to be in a working state to provide value to the community."
Maybe you could discuss this issue with the audit team. I think this is not the right way to go on with the project.

**Comment by tspearing** [comment]
@stweyel, what Justin said wasn't a mistake. Bucky's announcement refers to having a working product, it just doesn't need to be polished.

**Comment by angle943** [comment]
yes, when I wrote that comment, I meant that milestone1, which encompasses all ten objevtives that you have listed, are approved for 76,000. Not individually.

Sorry that wasn't clearer. BTW, i've been out of the project review process, so it'll probably be best to discuss this further with @tspearing and @manishram for further clarification

**Comment by stweyel** [comment]
@angle943 Thanks for answering.
@tspearing @manishram this has to be sorted! Not just for this project but also for future reference on how we (the community) deal with such matters.
Sum up of facts:
- The project was clearly proposed with 10 milestones if you look at the roadmap #167. These follow common concepts of milestones in context of a website as you e.g. can find here: https://digitalagencynetwork.com/website-design-process-milestones-timeline/ or here: https://www.idesignstudios.com/milestones/
It also complies with general understanding of a milestone.
- EDIT:
This comment https://github.com/thenewboston-developers/Projects/issues/167#issuecomment-846492059 obviously refers to multiple milestones.
- The project was approved then with just one milestone containing 10 _objectives_ instead. That little change was missed by me.
- The reason for the milestone/objective exchange is still unclear and the modified approval of the proposed concept wasn't clarified or explained in any way. (if done on purpose)
- The consequence is that the whole project including all works has to be finished completely before any further payout will be accepted. This contradicts any idea of milestones (bounded to payouts) and also comparable project proposals/approvals.


IMHO due to the mentioned reasons it doesn't make sense to handle the project/milestones that way and i kindly ask to revert back to the original milestone submission. If this is not acceptable i request an comprehensible explanatory statement which clears things up and can be taken as reference for others to prepare for such issues.
I think this is an important matter of transparency for all contributors.

**Comment by tspearing** [comment]
@stweyel we will follow the old pattern for this project only as it was set up this way. It is not how future projects will be run.
Approved for 6000 TNBC.
